{-# LANGUAGE OverloadedStrings #-}

{- | Dataset-soundness report tests.

Each check gets a database built to trip exactly it, plus the negative controls
that keep it from crying wolf: a treatment activity whose reference is an input,
allocation that rounds (33.3 × 3), an ordinary input at zero, coproduct blocks
that share a name but not an identifier.
-}
module QualityReportSpec (spec) where

import Data.Aeson (decode, encode)
import qualified Data.Map.Strict as M
import Data.Text (Text)
import qualified Data.Text as T
import Data.UUID (UUID)
import qualified Data.UUID as UUID
import Test.Hspec

import API.DatabaseHandlers (qualityReportToAPI)
import API.Types (QualityCheckAPI (..), QualityOffenderAPI (..), QualityReportAPI (..))
import Database.Quality (
    QualityCheck (..),
    QualityOffender (..),
    QualityReport (..),
    qualityReport,
 )
import Types (
    Activity (..),
    BioDirection (..),
    BiosphereFlow (..),
    DeclaredShare (..),
    Exchange (..),
    FormulaCheck (..),
    LocationSource (..),
    NativeProcessId (..),
    Severity (..),
    SimpleDatabase (..),
    SupplierClaim (..),
    TechRole (..),
    TechnosphereFlow (..),
    Unit (..),
    WasteFlow (..),
    mkPedigree,
    noProperties,
 )

-- ---------------------------------------------------------------------------
-- UUID helpers: readable fixed identifiers.
-- ---------------------------------------------------------------------------

u :: String -> UUID
u suffix = read ("00000000-0000-0000-0000-0000000000" <> suffix)

kgUnit, unknownUnit, breadFlow, flourFlow, wasteFlow :: UUID
kgUnit = u "01"
unknownUnit = u "02"
breadFlow = u "03"
flourFlow = u "04"
wasteFlow = u "05"

m2Unit, transFromFlow, transToFlow :: UUID
m2Unit = u "06"
transFromFlow = u "07"
transToFlow = u "08"

bod5Flow, codFlow, docFlow, tocFlow, mercuryFlow :: UUID
bod5Flow = u "09"
codFlow = u "0c"
docFlow = u "0d"
tocFlow = u "0e"
mercuryFlow = u "0f"

actA, actB, actC, prodA, prodB, prodC :: UUID
actA = u "0a"
actB = u "0b"
actC = u "0c"
prodA = u "1a"
prodB = u "1b"
prodC = u "1c"

-- ---------------------------------------------------------------------------
-- Fixture building blocks
-- ---------------------------------------------------------------------------

-- | The same activity, filed in the source's obsolete category.
obsolete :: Activity -> Activity
obsolete act = act{activityClassification = M.insert "Category" "Others\\Obsolete" (activityClassification act)}

mkActivity :: Text -> [Exchange] -> Activity
mkActivity name = mkActivityAt name "FR"

mkActivityAt :: Text -> Text -> [Exchange] -> Activity
mkActivityAt name location exs =
    Activity
        { activityName = name
        , activityDescription = ["A described activity"]
        , activityDocumentation = []
        , activitySynonyms = M.empty
        , activityClassification = M.singleton "ISIC" "1071"
        , activityLocation = location
        , activityLocationSource = LocationDeclared
        , activityUnit = "kg"
        , exchanges = exs
        , activityParams = M.empty
        , activityParamExprs = M.empty
        , activityNativeType = Nothing
        , activityNativeId = Nothing
        , activityFormulaCheck = Nothing
        }

techExchange :: UUID -> Double -> TechRole -> Exchange
techExchange fid amount role =
    TechnosphereExchange
        { techFlowId = fid
        , techAmount = amount
        , techUnitId = kgUnit
        , techRole = role
        , techActivityLinkId = Nothing
        , techSupplierClaim = ClaimByProduct
        , techLocation = "FR"
        , techComment = Nothing
        , techPedigree = Nothing
        , techShare = Nothing
        , techClassification = M.empty
        , techProperties = noProperties
        }

reference :: UUID -> Exchange
reference fid = techExchange fid 1.0 ReferenceProduct

input :: UUID -> Double -> Exchange
input fid amount = techExchange fid amount Input

-- | A treatment activity is defined by the waste it consumes, not by an output.
referenceInput :: UUID -> Exchange
referenceInput fid = techExchange fid 1.0 ReferenceInput

-- | The same technosphere line with pedigree scores attached.
pedigreed :: Exchange -> Exchange
pedigreed ex = ex{techPedigree = mkPedigree 3 3 2 1 2}

-- | A biosphere exchange in the given unit.
mkBio :: UUID -> UUID -> Double -> Exchange
mkBio uid fid amount =
    BiosphereExchange
        { bioFlowId = fid
        , bioAmount = amount
        , bioUnitId = uid
        , bioDirection = Resource
        , bioLocation = "FR"
        , bioComment = Nothing
        , bioPedigree = Nothing
        }

-- | A land-use exchange, measured in m².
bioExchange :: UUID -> Double -> Exchange
bioExchange = mkBio m2Unit

-- | Waste generated by an activity, on its way to some treatment.
wasteOut :: UUID -> Exchange
wasteOut fid =
    WasteExchange
        { waFlowId = fid
        , waAmount = 1.0
        , waUnitId = kgUnit
        , waIsInput = False
        , waActivityLinkId = Nothing
        , waSupplierClaim = ClaimByProduct
        , waLocation = "FR"
        , waComment = Nothing
        , waPedigree = Nothing
        }

{- | Database from activities keyed by (activity, product), with the standard
flow and unit registries every fixture shares.
-}
dbOf :: [((UUID, UUID), Activity)] -> SimpleDatabase
dbOf acts =
    SimpleDatabase
        { sdbActivities = M.fromList acts
        , sdbTechFlows =
            M.fromList
                [ (breadFlow, TechnosphereFlow breadFlow "bread" kgUnit M.empty Nothing Nothing)
                , (flourFlow, TechnosphereFlow flourFlow "flour" kgUnit M.empty Nothing Nothing)
                ]
        , sdbBioFlows =
            M.fromList
                [ (transFromFlow, BiosphereFlow transFromFlow "Transformation, from forest" m2Unit M.empty Nothing Nothing Nothing)
                , (transToFlow, BiosphereFlow transToFlow "Transformation, to arable land" m2Unit M.empty Nothing Nothing Nothing)
                , (bod5Flow, BiosphereFlow bod5Flow "BOD5 (Biological Oxygen Demand)" kgUnit M.empty Nothing Nothing Nothing)
                , (codFlow, BiosphereFlow codFlow "COD, Chemical Oxygen Demand" kgUnit M.empty Nothing Nothing Nothing)
                , (docFlow, BiosphereFlow docFlow "DOC, Dissolved Organic Carbon" kgUnit M.empty Nothing Nothing Nothing)
                , (tocFlow, BiosphereFlow tocFlow "TOC, Total Organic Carbon" kgUnit M.empty Nothing Nothing Nothing)
                ]
        , sdbWasteFlows = M.fromList [(wasteFlow, WasteFlow wasteFlow "municipal waste" kgUnit M.empty Nothing Nothing)]
        , sdbUnits = M.fromList [(kgUnit, Unit kgUnit "kg" "kg" ""), (m2Unit, Unit m2Unit "m2" "m2" "")]
        }

-- | The report of a one-activity database, for the many single-defect cases.
reportOf :: Activity -> QualityReport
reportOf act = qualityReport "testdb" (dbOf [((actA, prodA), act)])

details :: QualityCheck -> [Text]
details = map qoDetail . qcOffenders

severities :: QualityCheck -> [Severity]
severities = map qoSeverity . qcOffenders

processIds :: QualityCheck -> [Text]
processIds = map qoProcessId . qcOffenders

-- | The canonical process id a finding on this (activity, product) entry carries.
pidOf :: UUID -> UUID -> Text
pidOf a p = UUID.toText a <> "_" <> UUID.toText p

{- | A one-activity database whose mercury input carries the given CAS (or
none), for the CAS check - its own registry so other fixtures stay CAS-free.
-}
casDbWith :: Maybe Text -> SimpleDatabase
casDbWith cas =
    (dbOf [((actA, prodA), mkActivity "smelter" [reference breadFlow, input mercuryFlow 1.0])])
        { sdbTechFlows =
            M.fromList
                [ (breadFlow, TechnosphereFlow breadFlow "bread" kgUnit M.empty Nothing Nothing)
                , (mercuryFlow, TechnosphereFlow mercuryFlow "mercury" kgUnit M.empty cas Nothing)
                ]
        }

-- | An activity carrying an allocation percentage and a source block identity.
allocated :: Text -> Maybe Double -> Maybe Text -> Activity
allocated name percent nativeId =
    (mkActivity name [(reference breadFlow){techShare = (`DeclaredShare` Nothing) <$> percent}])
        { activityNativeId = NativeProcessId <$> nativeId
        }

spec :: Spec
spec = do
    describe "reference product check" $ do
        it "flags an activity with no reference exchange" $ do
            let check = qrReferenceProduct (reportOf (mkActivity "no reference" [input flourFlow 1.0]))
            details check `shouldBe` ["0 reference exchanges instead of exactly one"]
            severities check `shouldBe` [DangerSev]
            processIds check `shouldBe` [pidOf actA prodA]

        it "flags an activity with two reference exchanges" $ do
            let check = qrReferenceProduct (reportOf (mkActivity "two references" [reference breadFlow, reference flourFlow]))
            details check `shouldBe` ["2 reference exchanges instead of exactly one"]

        it "passes an activity with exactly one reference exchange" $
            qcOffenders (qrReferenceProduct (reportOf (mkActivity "bread" [reference breadFlow, input flourFlow 1.0])))
                `shouldBe` []

        it "passes a treatment activity defined by its reference input" $
            qcOffenders (qrReferenceProduct (reportOf (mkActivity "waste treatment" [referenceInput wasteFlow])))
                `shouldBe` []

    describe "unallocated check" $ do
        it "names an activity still carrying a coproduct, with what would repair it" $ do
            let check = qrUnallocated (reportOf (mkActivity "mill" [reference flourFlow, techExchange breadFlow 0.2 Coproduct]))
            details check `shouldBe` ["2 product outputs, 2 without a declared share: state a share on every product row, or load the dataset already allocated"]
            severities check `shouldBe` [DangerSev]

        it "passes a process split from a block, whatever share it was given" $
            qcOffenders (qrUnallocated (reportOf (allocated "block" (Just 0) (Just "b1")))) `shouldBe` []

        it "passes an activity that displaces a product" $
            qcOffenders (qrUnallocated (reportOf (mkActivity "bakery" [reference breadFlow, techExchange flourFlow 0.5 AvoidedProduct]))) `shouldBe` []

    describe "allocation sums check" $ do
        it "passes coproducts of one block summing to 100%" $ do
            let db = dbOf [((actA, prodA), allocated "block" (Just 60) (Just "b1")), ((actA, prodB), allocated "block" (Just 40) (Just "b1"))]
            qcOffenders (qrAllocationSums (qualityReport "testdb" db)) `shouldBe` []

        it "flags coproducts summing to 90%, naming the sum" $ do
            let db = dbOf [((actA, prodA), allocated "block" (Just 60) (Just "b1")), ((actA, prodB), allocated "block" (Just 30) (Just "b1"))]
                check = qrAllocationSums (qualityReport "testdb" db)
            details check `shouldBe` ["allocation sums to 90.00% across 2 coproduct(s)"]
            severities check `shouldBe` [DangerSev]

        it "rounds the reported sum to two decimals, free of floating-point dust" $ do
            -- 33.3 + 33.3 + 3.3 is 69.89999999999999 as a double; the message
            -- must not say so, and the judgement still flags it.
            let db =
                    dbOf
                        [ ((actA, prodA), allocated "block" (Just 33.3) (Just "b1"))
                        , ((actA, prodB), allocated "block" (Just 33.3) (Just "b1"))
                        , ((actA, u "1c"), allocated "block" (Just 3.3) (Just "b1"))
                        ]
            details (qrAllocationSums (qualityReport "testdb" db))
                `shouldBe` ["allocation sums to 69.90% across 3 coproduct(s)"]

        it "tolerates source rounding (33.3 + 33.3 + 33.4)" $ do
            let db =
                    dbOf
                        [ ((actA, prodA), allocated "block" (Just 33.3) (Just "b1"))
                        , ((actA, prodB), allocated "block" (Just 33.3) (Just "b1"))
                        , ((actA, u "1c"), allocated "block" (Just 33.4) (Just "b1"))
                        ]
            qcOffenders (qrAllocationSums (qualityReport "testdb" db)) `shouldBe` []

        it "flags a NaN percentage, which every comparison would otherwise pass" $ do
            let db = dbOf [((actA, prodA), allocated "block" (Just (0 / 0)) (Just "b1"))]
            length (qcOffenders (qrAllocationSums (qualityReport "testdb" db))) `shouldBe` 1

        it "keeps same-named blocks under different activities apart" $ do
            -- Both blocks are internally complete at 100%. Merging them by name
            -- would sum to 200% and invent two findings. Their identifiers are
            -- what earns them two activities: the parser mints the UUID from
            -- the identifier, so only a block publishing none falls back to a
            -- name that another block may share.
            let db = dbOf [((actA, prodA), allocated "truncated name" (Just 100) (Just "b1")), ((actB, prodB), allocated "truncated name" (Just 100) (Just "b2"))]
            qcOffenders (qrAllocationSums (qualityReport "testdb" db)) `shouldBe` []

        it "flags a block where only some coproducts carry a percentage, without judging its sum" $ do
            -- The 60% alone is neither a good sum nor a bad one - the missing
            -- percentage is the defect, so it gets its own warning instead of
            -- a misdiagnosed danger.
            let db = dbOf [((actA, prodA), allocated "block" (Just 60) (Just "b1")), ((actA, prodB), allocated "block" Nothing (Just "b1"))]
                check = qrAllocationSums (qualityReport "testdb" db)
            details check `shouldBe` ["1 of 2 coproduct(s) carry no allocation percentage"]
            severities check `shouldBe` [WarningSev]

        it "leaves a block with no percentages at all alone" $ do
            let db = dbOf [((actA, prodA), allocated "block" Nothing (Just "b1")), ((actA, prodB), allocated "block" Nothing (Just "b1"))]
            qcOffenders (qrAllocationSums (qualityReport "testdb" db)) `shouldBe` []

        it "reports not-applicable on a database without allocation data" $ do
            let check = qrAllocationSums (reportOf (mkActivity "bread" [reference breadFlow]))
            qcApplicable check `shouldBe` False
            qcOffenders check `shouldBe` []

        it "reports applicable as soon as one entry carries a percentage" $
            qcApplicable (qrAllocationSums (reportOf (allocated "block" (Just 100) (Just "b1")))) `shouldBe` True

    describe "duplicate activities check" $ do
        it "flags the same name, location and reference product under distinct keys" $ do
            let db = dbOf [((actA, prodA), mkActivity "bread" [reference breadFlow]), ((actB, prodB), mkActivity "bread" [reference breadFlow])]
                check = qrDuplicateActivities (qualityReport "testdb" db)
            details check `shouldBe` ["2 identical entries (same name, location and reference product)"]
            map qoProductName (qcOffenders check) `shouldBe` [Just "bread"]
            severities check `shouldBe` [WarningSev]
            -- The finding covers several entries; it names the first so it
            -- stays navigable.
            processIds check `shouldBe` [pidOf actA prodA]

        it "passes the same name with a different reference product" $ do
            let db = dbOf [((actA, prodA), mkActivity "bakery" [reference breadFlow]), ((actB, prodB), mkActivity "bakery" [reference flourFlow])]
            qcOffenders (qrDuplicateActivities (qualityReport "testdb" db)) `shouldBe` []

        it "skips entries whose reference is broken, leaving them to the reference check" $ do
            let db = dbOf [((actA, prodA), mkActivity "bread" []), ((actB, prodB), mkActivity "bread" [])]
            qcOffenders (qrDuplicateActivities (qualityReport "testdb" db)) `shouldBe` []

    describe "duplicate products check" $ do
        it "flags two activities declaring one reference product" $ do
            -- The shape a stale export leaves behind: one block kept, one
            -- retired, both still declaring the product, their names apart by
            -- a typo so the duplicate-activities check cannot see them.
            let db =
                    dbOf
                        [ ((actA, prodA), mkActivity "pork, meat whitout bone" [reference breadFlow])
                        , ((actB, prodB), mkActivity "pork, meat without bone" [reference breadFlow])
                        ]
                check = qrDuplicateProducts (qualityReport "testdb" db)
            severities check `shouldBe` [WarningSev, WarningSev]
            details check
                `shouldBe` [ "this product is also the reference product of \"pork, meat without bone\" at the same location; an input naming it is answered by one of them"
                           , "this product is also the reference product of \"pork, meat whitout bone\" at the same location; an input naming it is answered by one of them"
                           ]
            processIds check `shouldBe` [pidOf actA prodA, pidOf actB prodB]
            map qoProductName (qcOffenders check) `shouldBe` [Just "bread", Just "bread"]

        it "passes a product only one activity declares" $ do
            let db =
                    dbOf
                        [ ((actA, prodA), mkActivity "bakery" [reference breadFlow])
                        , ((actB, prodB), mkActivity "mill" [reference flourFlow])
                        ]
            qcOffenders (qrDuplicateProducts (qualityReport "testdb" db)) `shouldBe` []

        it "skips entries whose reference is broken, leaving them to the reference check" $ do
            let db = dbOf [((actA, prodA), mkActivity "bread" []), ((actB, prodB), mkActivity "bread" [])]
            qcOffenders (qrDuplicateProducts (qualityReport "testdb" db)) `shouldBe` []

        it "passes one product made in two places" $ do
            -- How a database is meant to be written: ecoinvent produces one
            -- product in hundreds of geographies, and an input names the one
            -- it means. Only two at one location have nothing to tell them
            -- apart.
            let db =
                    dbOf
                        [ ((actA, prodA), mkActivityAt "bakery" "FR" [reference breadFlow])
                        , ((actB, prodB), mkActivityAt "bakery" "DE" [reference breadFlow])
                        ]
            qcOffenders (qrDuplicateProducts (qualityReport "testdb" db)) `shouldBe` []

    describe "suspicious amounts check" $ do
        it "flags a non-finite amount" $ do
            let check = qrSuspiciousAmounts (reportOf (mkActivity "bread" [reference breadFlow, input flourFlow (0 / 0)]))
            details check `shouldBe` ["exchange \"flour\" has a non-finite amount"]
            severities check `shouldBe` [DangerSev]

        it "flags an infinite amount" $
            length (qcOffenders (qrSuspiciousAmounts (reportOf (mkActivity "bread" [reference breadFlow, input flourFlow (1 / 0)]))))
                `shouldBe` 1

        it "flags a zero reference amount, which normalization divides by" $ do
            let check = qrSuspiciousAmounts (reportOf (mkActivity "bread" [techExchange breadFlow 0 ReferenceProduct]))
            details check `shouldBe` ["reference exchange \"bread\" has amount 0, which normalization would divide by"]

        it "passes an ordinary input at zero" $
            qcOffenders (qrSuspiciousAmounts (reportOf (mkActivity "bread" [reference breadFlow, input flourFlow 0])))
                `shouldBe` []

    describe "missing metadata check" $ do
        it "flags an empty description as info" $ do
            let check = qrMissingMetadata (reportOf (mkActivity "bread" [reference breadFlow]){activityDescription = []})
            details check `shouldBe` ["the dataset carries no description"]
            severities check `shouldBe` [InfoSev]

        it "flags a description of blank paragraphs" $
            details (qrMissingMetadata (reportOf (mkActivity "bread" [reference breadFlow]){activityDescription = ["", "   "]}))
                `shouldBe` ["the dataset carries no description"]

        it "flags a missing classification as info" $
            details (qrMissingMetadata (reportOf (mkActivity "bread" [reference breadFlow]){activityClassification = M.empty}))
                `shouldBe` ["the dataset carries no classification"]

        it "flags a missing location as warning" $ do
            let check = qrMissingMetadata (reportOf (mkActivity "bread" [reference breadFlow]){activityLocation = ""})
            details check `shouldBe` ["the dataset carries no location"]
            severities check `shouldBe` [WarningSev]

        it "flags exchanges whose unit is absent from the registry, with a count" $ do
            let act = mkActivity "bread" [reference breadFlow, (input flourFlow 1.0){techUnitId = unknownUnit}]
                check = qrMissingMetadata (reportOf act)
            details check `shouldBe` ["1 exchange(s) whose unit is absent from the unit registry"]
            severities check `shouldBe` [WarningSev]

        it "passes a fully documented activity" $
            qcOffenders (qrMissingMetadata (reportOf (mkActivity "bread" [reference breadFlow]))) `shouldBe` []

    describe "undeclared geography check" $ do
        it "flags a geography read off the dataset name as info" $ do
            let act = (mkActivity "bread {FR}" [reference breadFlow]){activityLocationSource = LocationInferredFromName}
                check = qrUndeclaredGeography (reportOf act)
            details check `shouldBe` ["geography \"FR\" was read from the dataset name, not declared by the source"]
            severities check `shouldBe` [InfoSev]

        it "flags a stand-in geography the source never declared" $
            details (qrUndeclaredGeography (reportOf (mkActivity "bread" [reference breadFlow]){activityLocation = "GLO", activityLocationSource = LocationUnspecified}))
                `shouldBe` ["the source declares no geography; \"GLO\" stands in for it"]

        it "flags an entry left with no geography at all" $
            details (qrUndeclaredGeography (reportOf (mkActivity "bread" [reference breadFlow]){activityLocation = "", activityLocationSource = LocationUnspecified}))
                `shouldBe` ["the source declares no geography"]

        it "passes a geography the source declared" $
            qcOffenders (qrUndeclaredGeography (reportOf (mkActivity "bread" [reference breadFlow]))) `shouldBe` []

    describe "formula consistency check" $ do
        it "flags an activity whose formulas diverge, with counts and the example" $ do
            let fc = FormulaCheck{fcEvaluated = 30, fcDivergent = 12, fcUnevaluable = 3, fcExample = Just "\"a*2\" evaluates to 5.0 but the dataset stores 4.0"}
                check = qrFormulaConsistency (reportOf ((mkActivity "bread" [reference breadFlow]){activityFormulaCheck = Just fc}))
            details check
                `shouldBe` ["12 of 30 evaluable formula(s) disagree with the stored amount (e.g. \"a*2\" evaluates to 5.0 but the dataset stores 4.0); 3 more could not be evaluated"]
            severities check `shouldBe` [InfoSev]

        it "passes an activity whose formulas only failed to evaluate" $ do
            let fc = FormulaCheck{fcEvaluated = 0, fcDivergent = 0, fcUnevaluable = 7, fcExample = Nothing}
                check = qrFormulaConsistency (reportOf ((mkActivity "bread" [reference breadFlow]){activityFormulaCheck = Just fc}))
            qcOffenders check `shouldBe` []
            qcApplicable check `shouldBe` True

        it "is not applicable to a database without any formula" $
            qcApplicable (qrFormulaConsistency (reportOf (mkActivity "bread" [reference breadFlow])))
                `shouldBe` False

    describe "truncated name collisions check" $ do
        -- An 80-character stem: names built on it only differ beyond the cap.
        let stem = T.replicate 80 "x"

        it "flags distinct names sharing their first 80 characters, one finding each" $ do
            let db =
                    dbOf
                        [ ((actA, prodA), mkActivity (stem <> "a") [reference breadFlow])
                        , ((actB, prodB), mkActivity (stem <> "b") [reference flourFlow])
                        ]
                check = qrTruncatedNameCollisions (qualityReport "testdb" db)
            details check
                `shouldBe` replicate 2 "shares its first 80 characters with 1 other name(s), which a SimaPro export would merge"
            severities check `shouldBe` [WarningSev, WarningSev]
            processIds check `shouldBe` [pidOf actA prodA, pidOf actB prodB]

        it "flags a name that is the exact 80-character prefix of a longer one" $ do
            let db =
                    dbOf
                        [ ((actA, prodA), mkActivity stem [reference breadFlow])
                        , ((actB, prodB), mkActivity (stem <> " tail") [reference flourFlow])
                        ]
            length (qcOffenders (qrTruncatedNameCollisions (qualityReport "testdb" db))) `shouldBe` 2

        it "passes identical long names, which are the duplicate check's business" $ do
            let db =
                    dbOf
                        [ ((actA, prodA), mkActivity (stem <> "a") [reference breadFlow])
                        , ((actB, prodB), mkActivity (stem <> "a") [reference breadFlow])
                        ]
            qcOffenders (qrTruncatedNameCollisions (qualityReport "testdb" db)) `shouldBe` []

        it "passes distinct names short enough to survive truncation" $ do
            let db =
                    dbOf
                        [ ((actA, prodA), mkActivity "bread" [reference breadFlow])
                        , ((actB, prodB), mkActivity "cake" [reference flourFlow])
                        ]
            qcOffenders (qrTruncatedNameCollisions (qualityReport "testdb" db)) `shouldBe` []

    describe "missing pedigree check" $ do
        it "is not applicable to a database without a single pedigree score" $ do
            let check = qrMissingPedigree (reportOf (mkActivity "bread" [reference breadFlow, input flourFlow 1.0]))
            qcApplicable check `shouldBe` False
            qcOffenders check `shouldBe` []

        it "counts the data lines missing pedigree scores, per entry" $ do
            let act = mkActivity "bread" [reference breadFlow, pedigreed (input flourFlow 1.0), input wasteFlow 2.0]
                check = qrMissingPedigree (reportOf act)
            details check `shouldBe` ["1 of 2 exchange(s) carry no pedigree scores"]
            severities check `shouldBe` [InfoSev]

        it "does not count the reference exchange, which is definitional" $ do
            let db =
                    dbOf
                        [ ((actA, prodA), mkActivity "bread" [reference breadFlow, pedigreed (input flourFlow 1.0)])
                        , ((actB, prodB), mkActivity "cake" [reference flourFlow, input breadFlow 1.0])
                        ]
                check = qrMissingPedigree (qualityReport "testdb" db)
            details check `shouldBe` ["1 of 1 exchange(s) carry no pedigree scores"]
            processIds check `shouldBe` [pidOf actB prodB]

        it "passes an entry whose every data line carries pedigree scores" $
            qcOffenders (qrMissingPedigree (reportOf (mkActivity "bread" [reference breadFlow, pedigreed (input flourFlow 1.0)])))
                `shouldBe` []

    describe "unconsumed products check" $ do
        it "flags the entry whose product no other entry consumes, and only it" $ do
            let db =
                    dbOf
                        [ ((actA, prodA), mkActivity "bread" [reference breadFlow, input flourFlow 1.0])
                        , ((actB, prodB), mkActivity "flour mill" [reference flourFlow])
                        ]
                check = qrUnconsumedProducts (qualityReport "testdb" db)
            details check `shouldBe` ["the reference product is never consumed within this database (expected for a final product)"]
            severities check `shouldBe` [InfoSev]
            processIds check `shouldBe` [pidOf actA prodA]
            map qoProductName (qcOffenders check) `shouldBe` [Just "bread"]

        it "counts a producer's waste output as use of the treatment" $ do
            let db =
                    dbOf
                        [ ((actA, prodA), mkActivity "bakery" [reference breadFlow, wasteOut wasteFlow])
                        , ((actB, prodB), mkActivity "incineration" [referenceInput wasteFlow])
                        ]
                check = qrUnconsumedProducts (qualityReport "testdb" db)
            -- The treatment is in use; only the bakery's bread is unconsumed.
            processIds check `shouldBe` [pidOf actA prodA]

        it "does not count a coproduct line as consumption" $ do
            let db =
                    dbOf
                        [ ((actA, prodA), mkActivity "bakery" [reference breadFlow])
                        , ((actB, prodB), mkActivity "mill" [reference flourFlow, techExchange breadFlow 0.2 Coproduct])
                        ]
            -- The mill also produces bread; nobody consumes bread or flour.
            length (qcOffenders (qrUnconsumedProducts (qualityReport "testdb" db))) `shouldBe` 2

        it "skips entries whose reference is broken, leaving them to the reference check" $
            qcOffenders (qrUnconsumedProducts (reportOf (mkActivity "no reference" [input flourFlow 1.0])))
                `shouldBe` []

    describe "unsupplied inputs check" $ do
        it "flags an input no reference product of the database supplies" $ do
            let db = dbOf [((actA, prodA), mkActivity "bread" [reference breadFlow, input flourFlow 1.0])]
                check = qrUnsuppliedInputs (qualityReport "testdb" db)
            severities check `shouldBe` [InfoSev]
            processIds check `shouldBe` [pidOf actA prodA]

        it "passes when the database produces what it consumes" $ do
            let db =
                    dbOf
                        [ ((actA, prodA), mkActivity "bread" [reference breadFlow, input flourFlow 1.0])
                        , ((actB, prodB), mkActivity "flour mill" [reference flourFlow])
                        ]
            qcOffenders (qrUnsuppliedInputs (qualityReport "testdb" db)) `shouldBe` []

        it "says nothing about a biosphere exchange, which has no supplier" $ do
            let db = dbOf [((actA, prodA), mkActivity "bread" [reference breadFlow, bioExchange flourFlow 1.0])]
            qcOffenders (qrUnsuppliedInputs (qualityReport "testdb" db)) `shouldBe` []

    describe "obsolete inputs check" $ do
        it "flags an input only a retired dataset supplies" $ do
            let db =
                    dbOf
                        [ ((actA, prodA), mkActivity "bread" [reference breadFlow, input flourFlow 1.0])
                        , ((actB, prodB), obsolete (mkActivity "old flour mill" [reference flourFlow]))
                        ]
                check = qrObsoleteInputs (qualityReport "testdb" db)
            severities check `shouldBe` [WarningSev]
            processIds check `shouldBe` [pidOf actA prodA]
            map qoProductName (qcOffenders check) `shouldBe` [Just "flour"]

        it "says nothing when a live dataset also supplies the product" $ do
            -- The retired block and the one that replaced it declare one
            -- product; the live one is what the linker answers with.
            let db =
                    dbOf
                        [ ((actA, prodA), mkActivity "bread" [reference breadFlow, input flourFlow 1.0])
                        , ((actB, prodB), obsolete (mkActivity "old flour mill" [reference flourFlow]))
                        , ((actC, prodC), mkActivity "flour mill" [reference flourFlow])
                        ]
            qcOffenders (qrObsoleteInputs (qualityReport "testdb" db)) `shouldBe` []

        it "says nothing about a database whose datasets are all in service" $ do
            let db =
                    dbOf
                        [ ((actA, prodA), mkActivity "bread" [reference breadFlow, input flourFlow 1.0])
                        , ((actB, prodB), mkActivity "flour mill" [reference flourFlow])
                        ]
            qcOffenders (qrObsoleteInputs (qualityReport "testdb" db)) `shouldBe` []

    describe "land transformation balance check" $ do
        it "flags an activity whose transformed-from and transformed-to areas diverge" $ do
            let act = mkActivity "land clearing" [reference breadFlow, bioExchange transFromFlow 10, bioExchange transToFlow 4]
                check = qrLandTransformationBalance (reportOf act)
            details check `shouldBe` ["land transformation is unbalanced: 10.000 m2 transformed from vs 4.000 m2 transformed to (60.00% apart)"]
            severities check `shouldBe` [WarningSev]

        it "passes an activity whose from and to areas match within rounding" $
            qcOffenders (qrLandTransformationBalance (reportOf (mkActivity "rotation" [reference breadFlow, bioExchange transFromFlow 10, bioExchange transToFlow 10.05])))
                `shouldBe` []

        it "sums several transformation lines on each side before comparing" $
            -- 6 + 4 from balances 10 to: the activity is fine only once summed.
            qcOffenders (qrLandTransformationBalance (reportOf (mkActivity "mosaic" [reference breadFlow, bioExchange transFromFlow 6, bioExchange transFromFlow 4, bioExchange transToFlow 10])))
                `shouldBe` []

        it "is not applicable to a database whose activities use no transformation flow" $ do
            let check = qrLandTransformationBalance (reportOf (mkActivity "bread" [reference breadFlow]))
            qcApplicable check `shouldBe` False
            qcOffenders check `shouldBe` []

    describe "oxygen demand order check" $ do
        it "flags an entry whose BOD5 exceeds its COD" $ do
            let act = mkActivity "effluent" [reference breadFlow, mkBio kgUnit bod5Flow 5, mkBio kgUnit codFlow 3]
                check = qrOxygenDemandOrder (reportOf act)
            details check `shouldBe` ["BOD5 (5.000) exceeds COD (3.000) in this entry - the biological oxygen demand cannot exceed the chemical"]
            severities check `shouldBe` [WarningSev]

        it "flags an entry whose DOC exceeds its TOC" $
            details (qrOxygenDemandOrder (reportOf (mkActivity "leachate" [reference breadFlow, mkBio kgUnit docFlow 2, mkBio kgUnit tocFlow 1])))
                `shouldBe` ["DOC (2.000) exceeds TOC (1.000) in this entry - the dissolved organic carbon cannot exceed the total"]

        it "passes an entry whose BOD5 is below its COD" $
            qcOffenders (qrOxygenDemandOrder (reportOf (mkActivity "effluent" [reference breadFlow, mkBio kgUnit bod5Flow 2, mkBio kgUnit codFlow 5])))
                `shouldBe` []

        it "does not flag a BOD5 present with no COD to compare it against" $
            qcOffenders (qrOxygenDemandOrder (reportOf (mkActivity "partial" [reference breadFlow, mkBio kgUnit bod5Flow 5])))
                `shouldBe` []

        it "is not applicable to a database with no oxygen-demand flow" $ do
            let check = qrOxygenDemandOrder (reportOf (mkActivity "bread" [reference breadFlow]))
            qcApplicable check `shouldBe` False
            qcOffenders check `shouldBe` []

    describe "invalid CAS number check" $ do
        it "flags a flow whose CAS check digit does not confirm the number" $ do
            let check = qrInvalidCas (qualityReport "testdb" (casDbWith (Just "7439-92-2")))
            details check `shouldBe` ["CAS number \"7439-92-2\" is not a valid CAS registry number"]
            map qoProductName (qcOffenders check) `shouldBe` [Just "mercury"]
            severities check `shouldBe` [WarningSev]
            processIds check `shouldBe` [pidOf actA prodA]

        it "passes a flow whose CAS check digit is correct" $
            qcOffenders (qrInvalidCas (qualityReport "testdb" (casDbWith (Just "7439-92-1")))) `shouldBe` []

        it "accepts the zero-padded spelling of a valid CAS" $
            qcOffenders (qrInvalidCas (qualityReport "testdb" (casDbWith (Just "007439-92-1")))) `shouldBe` []

        it "flags a CAS that is not three dash-separated numbers" $
            length (qcOffenders (qrInvalidCas (qualityReport "testdb" (casDbWith (Just "not-a-cas"))))) `shouldBe` 1

        it "is not applicable to a database whose flows carry no CAS" $ do
            let check = qrInvalidCas (qualityReport "testdb" (casDbWith Nothing))
            qcApplicable check `shouldBe` False
            qcOffenders check `shouldBe` []

    describe "allocation range check" $ do
        it "flags an allocation percentage above 100" $ do
            let check = qrAllocationOutOfRange (reportOf (allocated "block" (Just 120) (Just "b1")))
            details check `shouldBe` ["allocation percentage is 120.00%, outside the 0-100% range"]
            severities check `shouldBe` [WarningSev]

        it "flags a negative allocation percentage" $
            details (qrAllocationOutOfRange (reportOf (allocated "block" (Just (-20)) (Just "b1"))))
                `shouldBe` ["allocation percentage is -20.00%, outside the 0-100% range"]

        it "passes percentages within the range, including the bounds" $ do
            let db = dbOf [((actA, prodA), allocated "b" (Just 0) (Just "x")), ((actB, prodB), allocated "c" (Just 100) (Just "y"))]
            qcOffenders (qrAllocationOutOfRange (qualityReport "testdb" db)) `shouldBe` []

        it "is not applicable to a database without allocation data" $
            qcApplicable (qrAllocationOutOfRange (reportOf (mkActivity "bread" [reference breadFlow]))) `shouldBe` False

    describe "unmeasurable amount check" $ do
        it "flags an amount smaller than a single atom" $ do
            let check = qrUnmeasurableAmounts (reportOf (mkActivity "bread" [reference breadFlow, input flourFlow 4.11e-37]))
            details check `shouldBe` ["exchange \"flour\" carries 4.110e-37 kg, smaller than anything a measurement can yield"]
            severities check `shouldBe` [WarningSev]

        it "flags a negative amount of the same magnitude" $
            length (qcOffenders (qrUnmeasurableAmounts (reportOf (mkActivity "bread" [reference breadFlow, input flourFlow (-4.11e-37)])))) `shouldBe` 1

        it "flags an unmeasurable reference amount as danger, since normalization divides by it" $ do
            let check = qrUnmeasurableAmounts (reportOf (mkActivity "bread" [techExchange breadFlow 4.11e-37 ReferenceProduct]))
            details check `shouldBe` ["reference exchange \"bread\" carries 4.110e-37 kg, smaller than anything a measurement can yield, and normalization divides by it"]
            severities check `shouldBe` [DangerSev]

        it "flags a negative unmeasurable reference amount as danger too" $
            severities (qrUnmeasurableAmounts (reportOf (mkActivity "bread" [techExchange breadFlow (-4.11e-37) ReferenceProduct])))
                `shouldBe` [DangerSev]

        it "passes a small but measurable trace amount" $
            qcOffenders (qrUnmeasurableAmounts (reportOf (mkActivity "bread" [reference breadFlow, input flourFlow 1e-15]))) `shouldBe` []

        it "passes an amount at exactly the floor" $
            qcOffenders (qrUnmeasurableAmounts (reportOf (mkActivity "bread" [reference breadFlow, input flourFlow 1e-27]))) `shouldBe` []

        it "passes an amount of exactly zero, which says the input is absent" $
            qcOffenders (qrUnmeasurableAmounts (reportOf (mkActivity "bread" [reference breadFlow, input flourFlow 0]))) `shouldBe` []

    describe "report header" $
        it "counts one process per (activity, product) entry" $ do
            let db = dbOf [((actA, prodA), mkActivity "bread" [reference breadFlow]), ((actB, prodB), mkActivity "cake" [reference flourFlow])]
            qrProcessCount (qualityReport "testdb" db) `shouldBe` 2

    describe "wire projection" $ do
        it "caps the offender list but keeps the full count" $ do
            let act = (mkActivity "bread" [reference breadFlow]){activityDescription = [], activityClassification = M.empty}
                check = qraMissingMetadata (qualityReportToAPI (Just 1) (reportOf act))
            qcaOffenderCount check `shouldBe` 2
            length (qcaOffenders check) `shouldBe` 1

        it "returns every offender when no limit is given" $ do
            let act = (mkActivity "bread" [reference breadFlow]){activityDescription = [], activityClassification = M.empty}
            length (qcaOffenders (qraMissingMetadata (qualityReportToAPI Nothing (reportOf act)))) `shouldBe` 2

        it "orders findings worst-first, so a cap keeps the worst" $ do
            -- Missing location (warning) must outrank missing description (info).
            let act = (mkActivity "bread" [reference breadFlow]){activityDescription = [], activityLocation = ""}
            map qoaSeverity (qcaOffenders (qraMissingMetadata (qualityReportToAPI Nothing (reportOf act))))
                `shouldBe` [WarningSev, InfoSev]

        it "carries the process id through to the wire" $ do
            let act = mkActivity "no reference" [input flourFlow 1.0]
            map qoaProcessId (qcaOffenders (qraReferenceProduct (qualityReportToAPI Nothing (reportOf act))))
                `shouldBe` [pidOf actA prodA]

        it "carries applicable through to the wire" $
            qcaApplicable (qraAllocationSums (qualityReportToAPI Nothing (reportOf (mkActivity "bread" [reference breadFlow]))))
                `shouldBe` False

    describe "severity wire codes" $ do
        it "round-trips every severity through JSON" $
            map (decode . encode) [DangerSev, WarningSev, InfoSev]
                `shouldBe` [Just DangerSev, Just WarningSev, Just InfoSev]

        it "encodes as stable lowercase codes, not constructor names" $
            encode [DangerSev, WarningSev, InfoSev] `shouldBe` "[\"danger\",\"warning\",\"info\"]"

        it "rejects an unknown code rather than defaulting" $
            (decode "\"bogus\"" :: Maybe Severity) `shouldBe` Nothing
