#!/bin/bash
# Deploy the coverage report generated by ./build.sh --coverage to gh-pages.
# Usage: ./deploy-coverage.sh
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
COVERAGE_DIR="$SCRIPT_DIR/coverage-report"

if [[ ! -f "$COVERAGE_DIR/hpc_index.html" ]]; then
    echo "No coverage report found. Run ./build.sh --coverage first."
    exit 1
fi

GH_PAGES_DIR=$(mktemp -d)
git worktree add "$GH_PAGES_DIR" gh-pages
rsync -a --delete --exclude='.git' "$COVERAGE_DIR/" "$GH_PAGES_DIR/"
SUMMARY=$(grep -h "expressions used" "$COVERAGE_DIR/hpc_index.html" 2>/dev/null | head -1 | sed 's/<[^>]*>//g' | tr -d ' \n' || echo "coverage update")
(cd "$GH_PAGES_DIR" && git add -A && git commit -m "coverage: $SUMMARY" && git push origin gh-pages)
git worktree remove "$GH_PAGES_DIR"
echo "Deployed: https://ccomb.github.io/volca/hpc_index.html"
