#!/bin/bash
# Build the volca Docker image
# Run from the volca directory

set -e

cd "$(dirname "$0")"

GIT_HASH=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
if ! git diff --quiet HEAD 2>/dev/null; then
    GIT_HASH="${GIT_HASH}-dirty"
fi
GIT_TAG=$(git describe --tags --exact-match HEAD 2>/dev/null || echo "")
CABAL_VERSION=$(grep "^version:" volca.cabal | awk '{print $2}')

# Generate Version.hs (same as build.sh, since .git is excluded from Docker context)
cat > src/Version.hs << EOF
-- AUTO-GENERATED by docker-build.sh -- do not edit
module Version where

version, gitHash, gitTag, buildTarget :: String
version = "$CABAL_VERSION"
gitHash = "$GIT_HASH"
gitTag = "$GIT_TAG"
buildTarget = "linux"
EOF

docker build \
    --build-arg GIT_HASH="$GIT_HASH" \
    -t volca .
