#!/bin/bash
# Generate the build-time modules: src/Version.hs (build metadata) and
# src/Builtin/Literals.hs (the reference tables and the method the engine carries).
# Uses git if available, falls back to GIT_HASH/GIT_TAG/BUILD_TARGET env vars.
set -e

cd "$(dirname "$0")"

GIT_HASH="${GIT_HASH:-$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")}"
# Append -dirty if working tree is dirty (only when git is available)
if [ "$GIT_HASH" != "unknown" ] && git rev-parse --git-dir >/dev/null 2>&1; then
    git diff --quiet HEAD 2>/dev/null || GIT_HASH="${GIT_HASH}-dirty"
fi
GIT_TAG="${GIT_TAG:-$(git describe --tags --exact-match HEAD 2>/dev/null || echo "")}"
VERSION=$(grep "^version:" volca.cabal | awk '{print $2}')
BUILD_TARGET="${BUILD_TARGET:-linux}"

cat > src/Version.hs << EOF
-- AUTO-GENERATED by gen-version.sh -- do not edit
module Version where

version, gitHash, gitTag, buildTarget :: String
version = "$VERSION"
gitHash = "$GIT_HASH"
gitTag = "$GIT_TAG"
buildTarget = "$BUILD_TARGET"
EOF

echo "Generated src/Version.hs (hash=$GIT_HASH, target=$BUILD_TARGET)"

# The reference tables and the method the engine carries. Read from data/ at
# build time so a binary downloaded on its own scores with them; base64 keeps the generated
# source ASCII whatever the CSV holds, and Builtin decodes it once at startup.
# base64 wraps lines on some platforms and not others, hence the tr.
b64() { base64 < "$1" | tr -d '\n'; }
DATA_VERSION=$(tr -d '[:space:]' < data/VERSION)
mkdir -p src/Builtin
cat > src/Builtin/Literals.hs << EOF
-- AUTO-GENERATED by gen-version.sh -- do not edit
module Builtin.Literals where

dataVersion :: String
dataVersion = "$DATA_VERSION"

flowsCsv, compartmentsCsv, unitsCsv, energyDensityCsv, geographiesCsv :: String
flowsCsv = "$(b64 data/flows.csv)"
compartmentsCsv = "$(b64 data/compartments.csv)"
unitsCsv = "$(b64 data/units.csv)"
energyDensityCsv = "$(b64 data/energy_density.csv)"
geographiesCsv = "$(b64 data/geographies.csv)"

plainIndicatorsCsv :: String
plainIndicatorsCsv = "$(b64 data/methods/plain-indicators.csv)"
EOF

echo "Generated src/Builtin/Literals.hs (data version $DATA_VERSION)"
