#!/usr/bin/env python3
"""Generate the pyvolca API reference as markdown.

Walks every name in ``volca.__all__`` and emits a structured reference.
The output is appended to README.md (between BEGIN/END markers) so PyPI
sees it, and also written as a standalone artifact under
``www/generated/pyvolca/`` so the Starlight guide can pull it in.

Usage:
    python scripts/gen_api_md.py        # writes to stdout

Stdlib only — pyvolca's only dependency stays ``requests``.
"""

from __future__ import annotations

import dataclasses
import inspect
import io
import sys
import typing
from pathlib import Path

# Ensure the in-tree source is importable regardless of cwd.
ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

import volca  # noqa: E402


def _first_line(doc: str | None) -> str:
    if not doc:
        return ""
    for line in doc.strip().splitlines():
        line = line.strip()
        if line:
            return line
    return ""


def _format_type(t: object) -> str:
    """Render a type annotation for a markdown table cell."""
    if isinstance(t, type):
        # Bare class — render its bare name (`str`, not `<class 'str'>`).
        return t.__name__
    s = str(t)
    s = s.replace("typing.", "")
    # Strip module prefixes like `volca.types.Activity` → `Activity`.
    s = s.replace("volca.types.", "").replace("volca.client.", "")
    # ForwardRef-ish wrappers occasionally show up; strip the boilerplate.
    s = s.replace("ForwardRef(", "").replace(")", "")
    return s


def _format_signature(sig: inspect.Signature) -> str:
    """Render a Signature in clean ``(arg: Type = default)`` form.

    Builds the string from parameters directly so that string-form
    annotations (from ``from __future__ import annotations``) lose their
    enclosing quotes without also stripping quotes from string defaults.
    """
    parts: list[str] = []
    seen_kw_only_marker = False
    seen_positional = False
    for p in sig.parameters.values():
        if p.name == "self":
            continue
        if p.kind is p.VAR_POSITIONAL:
            parts.append(f"*{p.name}")
            seen_kw_only_marker = True
            seen_positional = True
            continue
        if p.kind is p.KEYWORD_ONLY and not seen_kw_only_marker:
            parts.append("*")
            seen_kw_only_marker = True
        if p.kind is p.VAR_KEYWORD:
            parts.append(f"**{p.name}")
            continue
        seen_positional = True
        chunk = p.name
        if p.annotation is not p.empty:
            ann = p.annotation if isinstance(p.annotation, str) else _format_type(p.annotation)
            ann = ann.replace("volca.types.", "").replace("volca.client.", "")
            # Strip surrounding quotes from forward-ref string literals
            # (e.g. ``client: "Client"`` under ``from __future__ import annotations``).
            if len(ann) >= 2 and ann[0] in {"'", '"'} and ann[-1] == ann[0]:
                ann = ann[1:-1]
            chunk += f": {ann}"
        if p.default is not p.empty:
            chunk += f" = {p.default!r}"
        parts.append(chunk)
    rendered = "(" + ", ".join(parts) + ")"
    if sig.return_annotation is not sig.empty:
        ret = sig.return_annotation
        ret_str = ret if isinstance(ret, str) else _format_type(ret)
        ret_str = ret_str.replace("volca.types.", "").replace("volca.client.", "")
        rendered += f" -> {ret_str}"
    if not seen_positional and parts == []:
        rendered = "()"
    return rendered


def _is_autogenerated_dataclass_doc(cls: type, doc: str) -> bool:
    """True if the docstring is the synthesized ``Cls(field=…, …)`` form."""
    if not doc:
        return False
    return doc.startswith(f"{cls.__name__}(")


def _public_members(cls: type) -> tuple[list[tuple[str, str, str]], list[tuple[str, str]]]:
    """Return (methods, properties) for ``cls``.

    methods: (name, formatted_signature, first-line docstring)
    properties: (name, first-line docstring)
    """
    methods: list[tuple[str, str, str]] = []
    properties: list[tuple[str, str]] = []
    for name, member in sorted(vars(cls).items()):
        if name.startswith("_"):
            continue
        if isinstance(member, property):
            doc = inspect.getdoc(member.fget) or ""
            properties.append((name, _first_line(doc)))
            continue
        if not callable(member):
            continue
        try:
            sig_str = _format_signature(inspect.signature(member))
        except (TypeError, ValueError):
            sig_str = "()"
        doc = inspect.getdoc(member) or ""
        methods.append((name, sig_str, _first_line(doc)))
    return methods, properties


def render_class(cls: type, buf: io.StringIO) -> None:
    """Render a class with its public methods."""
    buf.write(f"### `{cls.__name__}`\n\n")
    cls_doc = inspect.getdoc(cls)
    if cls_doc:
        buf.write(cls_doc + "\n\n")
    try:
        init_sig = _format_signature(inspect.signature(cls))
        buf.write(f"**Constructor**: `{cls.__name__}{init_sig}`\n\n")
    except (TypeError, ValueError):
        pass
    methods, properties = _public_members(cls)
    if properties:
        buf.write("**Properties**:\n\n")
        for name, doc in properties:
            buf.write(f"- `{name}` — {doc or '(no docstring)'}\n")
        buf.write("\n")
    if methods:
        buf.write("**Methods**:\n\n")
        for name, sig_str, doc in methods:
            buf.write(f"- `{name}{sig_str}` — {doc or '(no docstring)'}\n")
        buf.write("\n")


def render_dataclass(cls: type, buf: io.StringIO) -> None:
    buf.write(f"### `{cls.__name__}`\n\n")
    doc = inspect.getdoc(cls) or ""
    if doc and not _is_autogenerated_dataclass_doc(cls, doc):
        buf.write(doc + "\n\n")
    fields = dataclasses.fields(cls)
    if not fields:
        return
    buf.write("| Field | Type | Default |\n")
    buf.write("|-------|------|---------|\n")
    for f in fields:
        # Escape pipes in type annotations (e.g. `str | None`) so they don't
        # break markdown table cells.
        type_str = _format_type(f.type).replace("|", "\\|")
        if f.default is not dataclasses.MISSING:
            default = repr(f.default)
        elif f.default_factory is not dataclasses.MISSING:  # type: ignore[misc]
            default = f"{f.default_factory.__name__}()"  # type: ignore[union-attr]
        else:
            default = "—"
        buf.write(f"| `{f.name}` | `{type_str}` | {default} |\n")
    buf.write("\n")


def render_function(fn: object, buf: io.StringIO) -> None:
    name = getattr(fn, "__name__", str(fn))
    try:
        sig_str = _format_signature(inspect.signature(fn))  # type: ignore[arg-type]
    except (TypeError, ValueError):
        sig_str = "()"
    buf.write(f"### `{name}{sig_str}`\n\n")
    doc = inspect.getdoc(fn)
    if doc:
        buf.write(doc + "\n\n")


def render_exception(cls: type, buf: io.StringIO) -> None:
    buf.write(f"### `{cls.__name__}`\n\n")
    doc = inspect.getdoc(cls)
    if doc:
        buf.write(doc + "\n\n")
    try:
        sig_str = _format_signature(inspect.signature(cls))
        buf.write(f"**Constructor**: `{cls.__name__}{sig_str}`\n\n")
    except (TypeError, ValueError):
        pass


def render_alias(name: str, alias: object, buf: io.StringIO) -> None:
    buf.write(f"### `{name}`\n\n")
    buf.write(f"Type alias: `{_format_type(alias)}`.\n\n")


def categorize(name: str) -> tuple[str, object]:
    """Return ``(kind, value)`` for a public name in volca."""
    value = getattr(volca, name)
    # Check typing constructs (Union, etc.) first — they pass `callable()`
    # but are not functions in any user-meaningful sense.
    if typing.get_origin(value) is typing.Union or hasattr(value, "__args__"):
        return "alias", value
    if inspect.isclass(value):
        if issubclass(value, BaseException):
            return "exception", value
        if dataclasses.is_dataclass(value):
            return "dataclass", value
        return "class", value
    if inspect.isfunction(value) or callable(value):
        return "function", value
    return "alias", value


def main() -> int:
    buf = io.StringIO()
    buf.write(
        "_This reference is generated from the installed package. "
        "Run `python scripts/gen_api_md.py` to regenerate._\n\n"
    )

    classes: list[type] = []
    exceptions: list[type] = []
    dataclasses_: list[type] = []
    functions: list[object] = []
    aliases: list[tuple[str, object]] = []

    for name in volca.__all__:
        kind, value = categorize(name)
        if kind == "class":
            classes.append(value)
        elif kind == "exception":
            exceptions.append(value)
        elif kind == "dataclass":
            dataclasses_.append(value)
        elif kind == "function":
            functions.append(value)
        else:
            aliases.append((name, value))

    if classes:
        buf.write("## Classes\n\n")
        for cls in classes:
            render_class(cls, buf)

    if exceptions:
        buf.write("## Exceptions\n\n")
        for cls in exceptions:
            render_exception(cls, buf)

    if dataclasses_:
        buf.write("## Data types\n\n")
        for cls in dataclasses_:
            render_dataclass(cls, buf)

    if functions:
        buf.write("## Functions\n\n")
        for fn in functions:
            render_function(fn, buf)

    if aliases:
        buf.write("## Type aliases\n\n")
        for name, alias in aliases:
            render_alias(name, alias, buf)

    sys.stdout.write(buf.getvalue())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
