{-# LANGUAGE BangPatterns #-}
{-# LANGUAGE OverloadedStrings #-}

{- | Chemical synonym expansion for the post-scoring suggester.

Loads a vendored snapshot of PubChem synonyms (regenerated by
@scripts/build_chem_synonyms.py@) into two indices:

* @csNameToCAS@ – lowercase canonical name → CAS, so any synonym we have
  acts as a key into the substance's full alias set.
* @csCASToTokens@ – CAS → union of normalized-name tokens across all
  synonyms. Pre-tokenized at load time so the hot-ish path stays cheap.

The expansion turns a flow name into a token set that includes every
alternate naming the snapshot knows. \"CO2\" then expands to
@{co2, carbon, dioxide, carbonic, anhydride, …}@ which can Jaccard-match
the CF named \"Carbon dioxide\" – the failure mode pure tokenization can
never solve.

CSV format (semicolon-delimited; SimaPro-CSV style):

>   cas;canonical_name;synonym1;synonym2;...

Empty file (header only) is allowed and yields 'emptyChemSynonyms', which
behaves as the identity expansion (no synonyms, just plain tokens).
-}
module Method.ChemSynonyms (
    ChemSynonyms,
    emptyChemSynonyms,
    loadChemSynonyms,
    parseChemSynonymsCSV,
    expandedTokens,
) where

import qualified Data.ByteString as BS
import Data.Map.Strict (Map)
import qualified Data.Map.Strict as M
import Data.Set (Set)
import qualified Data.Set as S
import Data.Text (Text)
import qualified Data.Text as T
import qualified Data.Text.Encoding as TE
import qualified Data.Text.Encoding.Error as TEE
import System.Directory (doesFileExist)

import SynonymDB (normalizeName)

{- | Indices over the vendored PubChem snapshot, keyed for two cheap lookups.

Build via 'loadChemSynonyms' or 'parseChemSynonymsCSV'; query via
'expandedTokens'. Construction normalizes names to lowercase and pre-splits
synonyms into tokens, so the caller never tokenizes per query.
-}
data ChemSynonyms = ChemSynonyms
    { csNameToCAS :: !(Map Text Text)
    , csCASToTokens :: !(Map Text (Set Text))
    }
    deriving (Eq, Show)

-- | Empty snapshot – every 'expandedTokens' query falls back to plain tokenization.
emptyChemSynonyms :: ChemSynonyms
emptyChemSynonyms = ChemSynonyms M.empty M.empty

{- | Load and parse a chem-synonyms CSV from disk.

Returns 'emptyChemSynonyms' (not an error) if the file is missing – the
suggester degrades gracefully to pure Jaccard, which is still useful.
Returns 'Left' only on actual parse failures.
-}
loadChemSynonyms :: FilePath -> IO (Either String ChemSynonyms)
loadChemSynonyms path = do
    exists <- doesFileExist path
    if not exists
        then pure (Right emptyChemSynonyms)
        else parseChemSynonymsCSV <$> BS.readFile path

{- | Parse CSV bytes into 'ChemSynonyms'. Skips the header row and any blank
or comment-prefixed (@#@) lines. Tolerates double-quoted fields.
-}
parseChemSynonymsCSV :: BS.ByteString -> Either String ChemSynonyms
parseChemSynonymsCSV bs =
    let txt = TE.decodeUtf8With TEE.lenientDecode bs
        ls = filter isDataLine (T.lines txt)
        rows = map (splitCSV ';') ls
        kept = [(T.strip cas, syns) | (cas : syns) <- rows, not (T.null (T.strip cas))]
     in Right (foldl' (flip addRow) emptyChemSynonyms kept)
  where
    isDataLine l =
        let s = T.strip l
         in not (T.null s)
                && not ("#" `T.isPrefixOf` s)
                && not ("cas;" `T.isPrefixOf` T.toLower s)

addRow :: (Text, [Text]) -> ChemSynonyms -> ChemSynonyms
addRow (cas, rawSyns) cs =
    let syns = filter (not . T.null) (map T.strip rawSyns)
        !tokens = S.fromList (concatMap (T.words . normalizeName) syns)
        !nameToCAS' = foldl' (\acc s -> M.insert (T.toLower s) cas acc) (csNameToCAS cs) syns
        !casToTokens' = M.insertWith S.union cas tokens (csCASToTokens cs)
     in cs{csNameToCAS = nameToCAS', csCASToTokens = casToTokens'}

{- | Tokenize a flow name and enrich it with the tokens of every synonym
known for the same CAS. Both sides of a candidate comparison call this
function, so they meet in token space even when the source names diverge.

Example: @expandedTokens cs \"CO2\" == {co2, carbon, dioxide, …}@ when the
snapshot maps name @\"co2\"@ to a CAS whose synonyms include
@\"Carbon dioxide\"@.
-}
expandedTokens :: ChemSynonyms -> Text -> Set Text
expandedTokens cs name =
    let lname = T.toLower (T.strip name)
        ownTokens = S.fromList (T.words (normalizeName name))
        synonymTokens = case M.lookup lname (csNameToCAS cs) of
            Nothing -> S.empty
            Just cas -> M.findWithDefault S.empty cas (csCASToTokens cs)
     in S.union ownTokens synonymTokens

-- | Tiny CSV splitter: respects double-quoted fields containing the delimiter.
splitCSV :: Char -> Text -> [Text]
splitCSV delim = go [] T.empty False
  where
    go acc cur inQuotes t = case T.uncons t of
        Nothing -> reverse (cur : acc)
        Just ('"', rest) -> go acc cur (not inQuotes) rest
        Just (c, rest)
            | c == delim && not inQuotes -> go (cur : acc) T.empty False rest
            | otherwise -> go acc (T.snoc cur c) inQuotes rest
