{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TypeFamilies #-}

module Types (
    module Types,
    UUID
) where

import Control.DeepSeq (NFData)
import Data.Aeson (FromJSON, ToJSON)
import qualified Data.Aeson as Aeson
import Data.Store (Store(..), Size(..), decodeEx, encode)
import Data.Word (Word32)
import Data.Hashable (Hashable)
import Data.Int (Int16, Int32)
import qualified Data.Map as M
import qualified Data.Set as S
import Data.Text (Text)
import qualified Data.Text as T
import qualified Data.Text.Encoding as TE
import Data.UUID (UUID)
import qualified Data.UUID as UUID
import qualified Data.Vector as V
import qualified Data.Vector.Unboxed as VU
import qualified Data.Vector.Generic as VG
import qualified Data.Vector.Generic.Mutable as VGM
import qualified Data.Vector.Unboxed.Mutable as VUM
import GHC.Generics (Generic, Generic1)

import Data.List (nub)
import SynonymDB (normalizeName)
import SynonymDB.Types (SynonymDB)

-- | Orphan Store instance for UUID (16 bytes, host-native word order)
instance Store UUID where
    size = ConstSize 16
    poke uuid = let (a, b, c, d) = UUID.toWords uuid
                in poke a >> poke b >> poke c >> poke d
    peek = UUID.fromWords <$> peek <*> peek <*> peek <*> peek

-- Note: UUID is now Data.UUID.UUID (16 bytes) instead of Text (~80+ bytes)
-- This saves ~2-3GB of RAM by reducing memory footprint from ~100,000+ UUID instances
-- NFData instance is provided by the uuid package; Store instance defined above

-- | Process identifier - compact Int16 index for efficient matrix operations
-- Maps to (activityUUID, productUUID) via Database.dbProcessIdTable
-- Based on EcoSpold filename pattern {activity_uuid}_{product_uuid}.spold
type ProcessId = Int16

-- | Type de flux : Technosphère (échange entre activités) ou Biosphère (échange avec l'environnement)
data FlowType = Technosphere | Biosphere
    deriving (Eq, Ord, Generic, NFData, Store)

-- | Représentation d'une unité (kg, MJ, m³, etc.)
data Unit = Unit
    { unitId :: !UUID -- Identifiant unique de l'unité
    , unitName :: !Text -- Nom de l'unité (e.g. "kg", "kilogram")
    , unitSymbol :: !Text -- Symbole (e.g. "kg", "MJ")
    , unitComment :: !Text -- Description/commentaire
    }
    deriving (Generic, NFData, Store)

-- | Substance - groups flows with the same chemical identity across databases
-- Used for flow matching between different LCA databases (ecoinvent, ILCD, SimaPro)
-- The substanceId links to the flow_mapping.json generated by the Python ETL script
data Substance = Substance
    { substanceId :: !Int -- Unique identifier within the mapping
    , substanceCanonicalName :: !Text -- Primary name for display
    , substanceCAS :: !(Maybe Text) -- CAS number (e.g. "7439-97-6" for Mercury)
    , substanceSynonyms :: !(S.Set Text) -- All normalized synonyms (lowercase)
    }
    deriving (Eq, Show, Generic, NFData, Store)

-- | Représentation d'un flux (matière, énergie, émission, etc.)
data Flow = Flow
    { flowId :: !UUID -- Identifiant du flux
    , flowName :: !Text -- Nom lisible
    , flowCategory :: !Text -- Catégorie/compartiment (e.g. air, water, soil, resource)
    , flowSubcompartment :: !(Maybe Text) -- Sous-catégorie (e.g. "urban air", "river water")
    , flowUnitId :: !UUID -- Référence vers l'unité par défaut dans UnitDB
    , flowType :: !FlowType -- Type de flux
    , flowSynonyms :: !(M.Map Text (S.Set Text)) -- Synonymes par langue (e.g. "en" -> {"BaP", "benzo[a]pyrene"})
    , flowCAS :: !(Maybe Text) -- CAS number for substance identification
    , flowSubstanceId :: !(Maybe Int) -- Link to Substance in FlowMappingData
    }
    deriving (Generic, NFData, Store)

-- | Échange dans un activité - Mirrors EcoSpold intermediateExchange/elementaryExchange structure
data Exchange
    = TechnosphereExchange
        { techFlowId :: !UUID -- Flow being exchanged
        , techAmount :: !Double -- Quantity exchanged
        , techUnitId :: !UUID -- Unit of measurement
        , techIsInput :: !Bool -- True if input
        , techIsReference :: !Bool -- True if reference product (main output)
        , techActivityLinkId :: !UUID -- Target activity ID (backward compatibility)
        , techProcessLinkId :: !(Maybe ProcessId) -- Target process ID (new field)
        , techLocation :: !Text -- Supplier location (EcoSpold1) or "" (EcoSpold2)
        }
    | BiosphereExchange
        { bioFlowId :: !UUID -- Flow being exchanged
        , bioAmount :: !Double -- Quantity exchanged
        , bioUnitId :: !UUID -- Unit of measurement
        , bioIsInput :: !Bool -- True for resource extraction, False for emissions
        , bioLocation :: !Text -- Exchange location (EcoSpold1) or "" (EcoSpold2)
        }
    deriving (Generic, NFData, Store)

-- | Helper functions for Exchange variants
exchangeFlowId :: Exchange -> UUID
exchangeFlowId (TechnosphereExchange fid _ _ _ _ _ _ _) = fid
exchangeFlowId (BiosphereExchange fid _ _ _ _) = fid

exchangeAmount :: Exchange -> Double
exchangeAmount (TechnosphereExchange _ amt _ _ _ _ _ _) = amt
exchangeAmount (BiosphereExchange _ amt _ _ _) = amt

exchangeUnitId :: Exchange -> UUID
exchangeUnitId (TechnosphereExchange _ _ uid _ _ _ _ _) = uid
exchangeUnitId (BiosphereExchange _ _ uid _ _) = uid

exchangeIsInput :: Exchange -> Bool
exchangeIsInput (TechnosphereExchange _ _ _ isInp _ _ _ _) = isInp
exchangeIsInput (BiosphereExchange _ _ _ isInp _) = isInp

exchangeIsReference :: Exchange -> Bool
exchangeIsReference (TechnosphereExchange _ _ _ _ isRef _ _ _) = isRef
exchangeIsReference (BiosphereExchange _ _ _ _ _) = False -- Biosphere exchanges are never reference products

-- | Get activity link ID (backward compatibility)
exchangeActivityLinkId :: Exchange -> Maybe UUID
exchangeActivityLinkId (TechnosphereExchange _ _ _ _ _ linkId _ _) =
    if linkId == UUID.nil then Nothing else Just linkId
exchangeActivityLinkId (BiosphereExchange _ _ _ _ _) = Nothing

-- | Get process link ID (new field)
exchangeProcessLinkId :: Exchange -> Maybe ProcessId
exchangeProcessLinkId (TechnosphereExchange _ _ _ _ _ _ processLinkId _) = processLinkId
exchangeProcessLinkId (BiosphereExchange _ _ _ _ _) = Nothing

-- | Get exchange location (for EcoSpold1 supplier lookup)
exchangeLocation :: Exchange -> Text
exchangeLocation (TechnosphereExchange _ _ _ _ _ _ _ loc) = loc
exchangeLocation (BiosphereExchange _ _ _ _ loc) = loc

-- | Check if exchange is technosphere
isTechnosphereExchange :: Exchange -> Bool
isTechnosphereExchange (TechnosphereExchange _ _ _ _ _ _ _ _) = True
isTechnosphereExchange (BiosphereExchange _ _ _ _ _) = False

-- | Check if exchange is biosphere
isBiosphereExchange :: Exchange -> Bool
isBiosphereExchange = not . isTechnosphereExchange

-- | Get unit information for an exchange
getUnitForExchange :: UnitDB -> Exchange -> Maybe Unit
getUnitForExchange unitDB exchange = M.lookup (exchangeUnitId exchange) unitDB

-- | Get unit name for an exchange (fallback to "unknown" if not found)
getUnitNameForExchange :: UnitDB -> Exchange -> Text
getUnitNameForExchange unitDB exchange =
    case getUnitForExchange unitDB exchange of
        Just unit -> unitName unit
        Nothing -> "unknown"

-- | Get unit information for a flow
getUnitForFlow :: UnitDB -> Flow -> Maybe Unit
getUnitForFlow unitDB flow = M.lookup (flowUnitId flow) unitDB

-- | Get unit name for a flow (fallback to "unknown" if not found)
getUnitNameForFlow :: UnitDB -> Flow -> Text
getUnitNameForFlow unitDB flow =
    case getUnitForFlow unitDB flow of
        Just unit -> unitName unit
        Nothing -> "unknown"

-- | Activité ACV de base (activité)
-- Note: ProcessId is the index in dbActivities vector, UUIDs stored in dbProcessIdTable
data Activity = Activity
    { activityName :: !Text -- Nom
    , activityDescription :: ![Text] -- Description générale (generalComment) par paragraphes
    , activitySynonyms :: !(M.Map Text (S.Set Text)) -- Synonymes par langue comme les flux
    , activityClassification :: !(M.Map Text Text) -- Classifications (ISIC, CPC, etc.)
    , activityLocation :: !Text -- Code de localisation (ex: FR, RER)
    , activityUnit :: !Text -- Unité de référence
    , exchanges :: ![Exchange] -- Liste des échanges
    }
    deriving (Generic, NFData, Store)

-- | Arbre de calcul ACV (représentation récursive)
data ActivityTree
    = Leaf !Activity
    | Node !Activity ![(Double, ActivityTree)] -- Activités et sous-activités pondérés

-- | Arbre avec détection de boucles pour export SVG
data LoopAwareTree
    = TreeLeaf !Activity
    | TreeNode !Activity ![(Double, Flow, LoopAwareTree)] -- Activity + (quantity, flow, subtree)
    | TreeLoop !UUID !Text !Int -- Loop reference: UUID + ActivityName + Depth

-- | Base de données des flux (dédupliquée)
type FlowDB = M.Map UUID Flow

-- | Base de données des unités (dédupliquée)
type UnitDB = M.Map UUID Unit

-- | Temporary Map structure used during database loading phase
-- Maps from (activityUUID, productUUID) pairs extracted from .spold filenames
-- This is converted to ActivityDB Vector during database construction
type ActivityMap = M.Map (UUID, UUID) Activity

-- | Base de données des activités - Vector for direct indexing by ProcessId (Int16)
-- Each spold file (activity_uuid_product_uuid.spold) becomes a separate entry
type ActivityDB = V.Vector Activity

-- | Index par nom de activité - permet la recherche par nom (insensible à la casse)
type NameIndex = M.Map Text [UUID] -- Nom -> Liste des UUIDs des activités

-- | Index par localisation - permet la recherche par zone géographique
type LocationIndex = M.Map Text [UUID] -- Location -> Liste des UUIDs des activités

-- | Index par flux - permet de trouver quels activités utilisent un flux donné
type FlowIndex = M.Map UUID [UUID] -- FlowID -> Liste des UUIDs des activités qui l'utilisent

-- | Index par catégorie de flux - permet la recherche par type de flux
type FlowCategoryIndex = M.Map Text [UUID] -- Category -> Liste des UUIDs des flux

-- | Index par type de flux - sépare Technosphere/Biosphere
type FlowTypeIndex = M.Map FlowType [UUID] -- FlowType -> Liste des UUIDs des flux

-- | Index des échanges par flux - permet de trouver tous les échanges utilisant un flux
type ExchangeIndex = M.Map UUID [(UUID, Exchange)] -- FlowID -> [(ActivityID, Exchange)]

-- | Index des échanges par activité - accès rapide aux échanges d'un activité
type ActivityExchangeIndex = M.Map UUID [Exchange] -- ActivityID -> [Exchange]

-- | Index des produits de référence - tous les outputs principaux
type ReferenceProductIndex = M.Map UUID [(UUID, Exchange)] -- FlowID -> [(ActivityID, Exchange)]

-- | Index des entrées par activité - sépare inputs/outputs pour recherches efficaces
type ActivityInputIndex = M.Map UUID [Exchange] -- ActivityID -> [Input Exchanges]

-- | Index des sorties par activité - sépare inputs/outputs pour recherches efficaces
type ActivityOutputIndex = M.Map UUID [Exchange] -- ActivityID -> [Output Exchanges]

-- | Index par unité de référence - permet la recherche par unité
type ActivityUnitIndex = M.Map Text [UUID] -- Unit -> Liste des UUIDs des activités

-- | Structure d'index complète pour recherches efficaces
-- Memory optimization: Removed unused exchange indexes that were duplicating 600K Exchange records
-- across 5 maps (idxExchangeByFlow, idxExchangeByActivity, idxReferenceProducts,
-- idxInputsByActivity, idxOutputsByActivity) - saves ~3-4GB RAM
data Indexes = Indexes
    { -- Index au niveau activité
      idxByName :: !NameIndex -- Recherche activités par nom
    , idxByLocation :: !LocationIndex -- Recherche activités par localisation
    , idxByFlow :: !FlowIndex -- Recherche activités utilisant un flux
    , idxByUnit :: !ActivityUnitIndex -- Recherche activités par unité de référence
    -- Index au niveau flux
    , idxFlowByCategory :: !FlowCategoryIndex -- Recherche flux par catégorie
    , idxFlowByType :: !FlowTypeIndex -- Recherche flux par type
    -- Note: Exchange-level indexes removed - exchanges can be accessed directly from Activity.exchanges
    }
    deriving (Generic, NFData, Store)

-- | Sparse matrix coordinate triplet (row, col, value)
-- Using Int32 for matrix indices to support large databases (up to 2 billion activities)
-- Unboxed to eliminate per-element boxing overhead (~48 bytes → 16 bytes per triple)
-- With ~800K triples, this saves ~25MB + significant GC pressure
data SparseTriple = SparseTriple {-# UNPACK #-} !Int32 {-# UNPACK #-} !Int32 {-# UNPACK #-} !Double
    deriving (Eq, Show, Generic)

-- Manual Unbox instance for SparseTriple to enable VU.Vector storage
newtype instance VU.MVector s SparseTriple = MV_SparseTriple (VU.MVector s (Int32, Int32, Double))
newtype instance VU.Vector SparseTriple = V_SparseTriple (VU.Vector (Int32, Int32, Double))

instance VGM.MVector VU.MVector SparseTriple where
    {-# INLINE basicLength #-}
    {-# INLINE basicUnsafeSlice #-}
    {-# INLINE basicOverlaps #-}
    {-# INLINE basicUnsafeNew #-}
    {-# INLINE basicInitialize #-}
    {-# INLINE basicUnsafeRead #-}
    {-# INLINE basicUnsafeWrite #-}
    basicLength (MV_SparseTriple v) = VGM.basicLength v
    basicUnsafeSlice i n (MV_SparseTriple v) = MV_SparseTriple $ VGM.basicUnsafeSlice i n v
    basicOverlaps (MV_SparseTriple v1) (MV_SparseTriple v2) = VGM.basicOverlaps v1 v2
    basicUnsafeNew n = MV_SparseTriple <$> VGM.basicUnsafeNew n
    basicInitialize (MV_SparseTriple v) = VGM.basicInitialize v
    basicUnsafeRead (MV_SparseTriple v) i = do
        (r, c, val) <- VGM.basicUnsafeRead v i
        return $ SparseTriple r c val
    basicUnsafeWrite (MV_SparseTriple v) i (SparseTriple r c val) =
        VGM.basicUnsafeWrite v i (r, c, val)

instance VG.Vector VU.Vector SparseTriple where
    {-# INLINE basicUnsafeFreeze #-}
    {-# INLINE basicUnsafeThaw #-}
    {-# INLINE basicLength #-}
    {-# INLINE basicUnsafeSlice #-}
    {-# INLINE basicUnsafeIndexM #-}
    basicUnsafeFreeze (MV_SparseTriple v) = V_SparseTriple <$> VG.basicUnsafeFreeze v
    basicUnsafeThaw (V_SparseTriple v) = MV_SparseTriple <$> VG.basicUnsafeThaw v
    basicLength (V_SparseTriple v) = VG.basicLength v
    basicUnsafeSlice i n (V_SparseTriple v) = V_SparseTriple $ VG.basicUnsafeSlice i n v
    basicUnsafeIndexM (V_SparseTriple v) i = do
        (r, c, val) <- VG.basicUnsafeIndexM v i
        return $ SparseTriple r c val

instance VU.Unbox SparseTriple

-- Store instance for cache serialization
instance Store SparseTriple where
    size = ConstSize 16 -- Int32 (4) + Int32 (4) + Double (8)
    poke (SparseTriple r c v) = poke r >> poke c >> poke v
    peek = SparseTriple <$> peek <*> peek <*> peek

-- NFData derived via Generic
instance NFData SparseTriple

-- | Store instance for VU.Vector SparseTriple (store has no built-in instance for custom Unbox types)
instance Store (VU.Vector SparseTriple) where
    size = VarSize $ \v -> 8 + VU.length v * 16
    poke v = do
        poke (VU.length v)
        VU.mapM_ poke v
    peek = do
        n <- peek
        VU.replicateM n peek

-- | Compute serialized size for a Store value
getSize :: Store a => a -> Int
getSize x = case size of
    ConstSize n -> n
    VarSize f -> f x

-- | Pre-computed matrix factorization for fast inventory calculations
data MatrixFactorization = MatrixFactorization
    { mfSystemMatrix :: !(VU.Vector SparseTriple) -- Cached (I - A) system matrix (unboxed)
    , mfActivityCount :: !Int32 -- Matrix dimension
    , mfDatabaseId :: !Text -- Database identifier for per-database cache lookup
    } deriving (Generic, NFData, Store)

-- | Index for looking up activities by their reference product attributes
-- Used for: (1) upstream link resolution for SimaPro data, (2) future product search
data ProductIndex = ProductIndex
    { piByUUID     :: !(M.Map UUID ProcessId)      -- Product flow UUID → ProcessId (for upstream links)
    , piByName     :: !(M.Map Text [ProcessId])    -- Normalized product name → [ProcessId] (for search)
    , piByLocation :: !(M.Map Text [ProcessId])    -- Location → [ProcessId] (for search)
    } deriving (Generic, NFData, Store)

-- | Empty product index (used as default when loading old cache files)
emptyProductIndex :: ProductIndex
emptyProductIndex = ProductIndex M.empty M.empty M.empty

-- | Base de données complète avec index pour recherches efficaces
data Database = Database
    { -- UUID interning tables for ProcessId ↔ (UUID, UUID) conversion
      dbProcessIdTable :: !(V.Vector (UUID, UUID)) -- ProcessId (Int16) → (activityUUID, productUUID)
    , dbProcessIdLookup :: !(M.Map (UUID, UUID) ProcessId) -- reverse lookup
    , dbActivityUUIDIndex :: !(M.Map UUID ProcessId) -- Activity UUID → ProcessId (for O(1) lookups)
    , dbActivityProductsIndex :: !(M.Map UUID [ProcessId]) -- Activity UUID → all ProcessIds (for multi-product activities)
    , dbProductIndex :: !ProductIndex -- Product flow → ProcessId lookups (for SimaPro links & product search)
    , dbActivities :: !ActivityDB -- Vector of activities indexed by ProcessId
    , dbFlows :: !FlowDB
    , dbUnits :: !UnitDB
    , dbIndexes :: !Indexes
    , -- Pre-computed sparse matrices for efficient LCA calculations (unboxed for memory efficiency)
      dbTechnosphereTriples :: !(VU.Vector SparseTriple) -- A matrix: activities × activities (sparse, unboxed)
    , dbBiosphereTriples :: !(VU.Vector SparseTriple) -- B matrix: biosphere flows × activities (sparse, unboxed)
    , dbActivityIndex :: !(V.Vector Int32) -- ProcessId → matrix index mapping (direct vector indexing)
    , dbBiosphereFlows :: !(V.Vector UUID) -- Ordered vector of biosphere flow UUIDs (source of truth for indexing, strict for memory efficiency)
    , dbActivityCount :: !Int32 -- Number of activities (matrix dimension)
    , dbBiosphereCount :: !Int32 -- Number of biosphere flows (matrix dimension)
    -- Cross-database linking (serialized to cache)
    , dbCrossDBLinks :: ![CrossDBLink] -- Cross-database supplier links (for chained solving)
    , dbDependsOn :: ![Text] -- Names of databases this database depends on
    -- Linking statistics (serialized to cache for setup page)
    , dbLinkingStats :: !CrossDBLinkingStats -- Cross-DB linking statistics (completeness, fallbacks, etc.)
    -- Runtime-only fields (not serialized to cache)
    , dbCachedFactorization :: !(Maybe MatrixFactorization) -- Pre-computed (I - A) for fast solves
    , dbSynonymDB :: !(Maybe SynonymDB) -- Embedded synonym database for flow matching
    , dbFlowsByName :: !(M.Map Text [Flow]) -- Flow name index for efficient lookup
    }
    deriving (Generic, NFData)

-- | Custom Store instance for Database
-- Only serializes persistent fields (not runtime-only: factorization, synonymDB, flowsByName)
instance Store Database where
    size = VarSize $ \db ->
        getSize (dbProcessIdTable db)
        + getSize (dbProcessIdLookup db)
        + getSize (dbActivityUUIDIndex db)
        + getSize (dbActivityProductsIndex db)
        + getSize (dbProductIndex db)
        + getSize (dbActivities db)
        + getSize (dbFlows db)
        + getSize (dbUnits db)
        + getSize (dbIndexes db)
        + getSize (dbTechnosphereTriples db)
        + getSize (dbBiosphereTriples db)
        + getSize (dbActivityIndex db)
        + getSize (dbBiosphereFlows db)
        + getSize (dbActivityCount db)
        + getSize (dbBiosphereCount db)
        + getSize (dbCrossDBLinks db)
        + getSize (dbDependsOn db)
        + getSize (dbLinkingStats db)

    poke db = do
        poke (dbProcessIdTable db)
        poke (dbProcessIdLookup db)
        poke (dbActivityUUIDIndex db)
        poke (dbActivityProductsIndex db)
        poke (dbProductIndex db)
        poke (dbActivities db)
        poke (dbFlows db)
        poke (dbUnits db)
        poke (dbIndexes db)
        poke (dbTechnosphereTriples db)
        poke (dbBiosphereTriples db)
        poke (dbActivityIndex db)
        poke (dbBiosphereFlows db)
        poke (dbActivityCount db)
        poke (dbBiosphereCount db)
        -- Cross-database linking fields
        poke (dbCrossDBLinks db)
        poke (dbDependsOn db)
        poke (dbLinkingStats db)
        -- Runtime-only fields are NOT serialized

    peek = do
        processIdTable <- peek
        processIdLookup <- peek
        activityUUIDIndex <- peek
        activityProductsIndex <- peek
        productIndex <- peek
        activities <- peek
        flows <- peek
        units <- peek
        indexes <- peek
        techTriples <- peek
        bioTriples <- peek
        activityIndex <- peek
        biosphereFlows <- peek
        activityCount <- peek
        biosphereCount <- peek
        crossDBLinks <- peek
        dependsOn <- peek
        linkingStats <- peek
        return Database
            { dbProcessIdTable = processIdTable
            , dbProcessIdLookup = processIdLookup
            , dbActivityUUIDIndex = activityUUIDIndex
            , dbActivityProductsIndex = activityProductsIndex
            , dbProductIndex = productIndex
            , dbActivities = activities
            , dbFlows = flows
            , dbUnits = units
            , dbIndexes = indexes
            , dbTechnosphereTriples = techTriples
            , dbBiosphereTriples = bioTriples
            , dbActivityIndex = activityIndex
            , dbBiosphereFlows = biosphereFlows
            , dbActivityCount = activityCount
            , dbBiosphereCount = biosphereCount
            -- Cross-database linking fields
            , dbCrossDBLinks = crossDBLinks
            , dbDependsOn = dependsOn
            , dbLinkingStats = linkingStats
            -- Runtime-only fields set to defaults
            , dbCachedFactorization = Nothing
            , dbSynonymDB = Nothing
            , dbFlowsByName = M.empty
            }

-- | Helper functions for ProcessId and Database operations

-- | Get activity by ProcessId (direct vector indexing)
getActivity :: Database -> ProcessId -> Maybe Activity
getActivity db pid
    | pid >= 0 && fromIntegral pid < V.length (dbActivities db) =
        Just $ dbActivities db V.! fromIntegral pid
    | otherwise = Nothing

-- | Find ProcessId from UUID pair
findProcessId :: Database -> UUID -> UUID -> Maybe ProcessId
findProcessId db actUUID prodUUID =
    M.lookup (actUUID, prodUUID) (dbProcessIdLookup db)

-- | Find any ProcessId matching an activity UUID
-- Returns the first ProcessId found with the given activity UUID.
-- ESSENTIAL for EcoSpold data: exchange links only contain activity UUIDs (not full ProcessIds),
-- so we must translate from UUID → ProcessId to handle multi-product activities.
findProcessIdByActivityUUID :: Database -> UUID -> Maybe ProcessId
findProcessIdByActivityUUID db searchUUID =
    M.lookup searchUUID (dbActivityUUIDIndex db)

-- | Find activity by activity UUID (returns first matching product)
-- ESSENTIAL for EcoSpold data: exchange links only contain activity UUIDs (not full ProcessIds).
-- When multiple products exist for one activity, this returns an arbitrary match.
-- Uses O(1) Map lookup for efficient resolution
findActivityByActivityUUID :: Database -> UUID -> Maybe Activity
findActivityByActivityUUID db searchUUID = do
    pid <- M.lookup searchUUID (dbActivityUUIDIndex db)
    getActivity db pid

-- | Find supplier ProcessId by product flow UUID
-- ESSENTIAL for SimaPro data: exchanges have techActivityLinkId = nil, but techFlowId is valid.
-- Uses the ProductIndex to resolve the supplier activity from the product flow.
findProcessIdByProductFlow :: Database -> UUID -> Maybe ProcessId
findProcessIdByProductFlow db flowUUID =
    M.lookup flowUUID (piByUUID $ dbProductIndex db)

-- | Search products by name (for future product search feature)
-- Returns all ProcessIds that produce products matching the given name
searchProductsByName :: Database -> Text -> [ProcessId]
searchProductsByName db query =
    M.findWithDefault [] (T.toLower query) (piByName $ dbProductIndex db)

-- | Search products by location (for future product search feature)
-- Returns all ProcessIds that produce products at the given location
searchProductsByLocation :: Database -> Text -> [ProcessId]
searchProductsByLocation db loc =
    M.findWithDefault [] loc (piByLocation $ dbProductIndex db)

-- | Convert ProcessId to UUID pair
processIdToUUIDs :: Database -> ProcessId -> Maybe (UUID, UUID)
processIdToUUIDs db pid
    | pid >= 0 && fromIntegral pid < V.length (dbProcessIdTable db) =
        Just $ dbProcessIdTable db V.! fromIntegral pid
    | otherwise = Nothing

-- | Convert ProcessId to Text representation for display (activityUUID_productUUID)
processIdToText :: Database -> ProcessId -> Text
processIdToText db pid =
    case processIdToUUIDs db pid of
        Just (actUUID, prodUUID) -> UUID.toText actUUID <> "_" <> UUID.toText prodUUID
        Nothing -> "invalid-process-id-" <> T.pack (show pid)

-- | Parse ProcessId from filename stem (requires Database for lookup)
parseProcessId :: Database -> Text -> Maybe ProcessId
parseProcessId db filename = case T.splitOn "_" filename of
    [actUUIDText, prodUUIDText] | not (T.null actUUIDText) && not (T.null prodUUIDText) ->
        case (UUID.fromText actUUIDText, UUID.fromText prodUUIDText) of
            (Just actUUID, Just prodUUID) -> findProcessId db actUUID prodUUID
            _ -> Nothing
    _ -> Nothing

-- | Add SynonymDB to a Database (used after loading from cache)
addSynonymDBToDatabase :: Database -> SynonymDB -> Database
addSynonymDBToDatabase db synDB = db { dbSynonymDB = Just synDB }

-- | Build the flow name index from the flow database
-- Groups flows by their normalized names for efficient lookup
buildFlowNameIndex :: FlowDB -> M.Map Text [Flow]
buildFlowNameIndex flowDB =
    M.fromListWith (++) $ concatMap flowEntries (M.elems flowDB)
  where
    flowEntries f =
        let primary = normalizeName (flowName f)
            synKeys = [ normalizeName syn
                      | syns <- M.elems (flowSynonyms f)
                      , syn <- S.toList syns ]
        in [(k, [f]) | k <- nub (primary : synKeys)]

-- | Add flow name index to a Database
addFlowNameIndexToDatabase :: Database -> Database
addFlowNameIndexToDatabase db = db { dbFlowsByName = buildFlowNameIndex (dbFlows db) }

-- | Add both SynonymDB and flow name index to a Database
-- Convenience function for post-load initialization
initializeRuntimeFields :: Database -> SynonymDB -> Database
initializeRuntimeFields db synDB =
    let db' = addSynonymDBToDatabase db synDB
    in addFlowNameIndexToDatabase db'

-- | Version simplifiée sans index (pour compatibilité)
-- Used during database loading, before conversion to final Vector structure
data SimpleDatabase = SimpleDatabase
    { sdbActivities :: !ActivityMap  -- Temporary Map structure
    , sdbFlows :: !FlowDB
    , sdbUnits :: !UnitDB
    }
    deriving (Generic, Store)

-- | Reconstruct SimpleDatabase from a fully-built Database
-- Used to skip re-parsing when a valid cache exists during staging
toSimpleDatabase :: Database -> SimpleDatabase
toSimpleDatabase db = SimpleDatabase
    { sdbActivities = M.fromList $ V.toList $ V.zipWith (,) (dbProcessIdTable db) (dbActivities db)
    , sdbFlows = dbFlows db
    , sdbUnits = dbUnits db
    }

-- | Catégorie d'impact (e.g. Changement climatique)
data ImpactCategory = ImpactCategory
    { categoryId :: !Text
    , categoryName :: !Text
    }
    deriving (Eq, Ord, Show)

-- | Blocking reason for cross-database linking failure
data LinkBlocker
    = NoNameMatch                      -- ^ Product not found at all
    | UnitIncompatible !Text !Text     -- ^ queryUnit, supplierUnit
    | LocationUnavailable !Text        -- ^ requestedLoc (no fallback found above threshold)
    deriving (Show, Eq, Generic, NFData, Store)

-- | Statistics from cross-database linking
-- Only essential state is stored; counts are derived via accessor functions.
data CrossDBLinkingStats = CrossDBLinkingStats
    { cdlLinks              :: ![CrossDBLink]                        -- ^ Resolved cross-DB links
    , cdlUnresolvedProducts :: !(M.Map Text (Int, LinkBlocker))     -- ^ Product name -> (count, reason)
    , cdlUnknownUnits       :: !(S.Set Text)                        -- ^ Unknown units from sdbUnits
    , cdlLocationFallbacks  :: ![(Text, Text, Text)]                -- ^ (product, requestedLoc, actualLoc)
    , cdlTotalInputs        :: !Int                                 -- ^ Total technosphere inputs at time of linking
    } deriving (Generic, NFData, Store)

-- | Empty stats
emptyCrossDBLinkingStats :: CrossDBLinkingStats
emptyCrossDBLinkingStats = CrossDBLinkingStats [] M.empty S.empty [] 0

-- | Merge two CrossDBLinkingStats
mergeCrossDBStats :: CrossDBLinkingStats -> CrossDBLinkingStats -> CrossDBLinkingStats
mergeCrossDBStats s1 s2 = CrossDBLinkingStats
    { cdlLinks = cdlLinks s1 ++ cdlLinks s2
    , cdlUnresolvedProducts = M.unionWith mergeUnresolved (cdlUnresolvedProducts s1) (cdlUnresolvedProducts s2)
    , cdlUnknownUnits = S.union (cdlUnknownUnits s1) (cdlUnknownUnits s2)
    , cdlLocationFallbacks = cdlLocationFallbacks s1 ++ cdlLocationFallbacks s2
    , cdlTotalInputs = cdlTotalInputs s1 + cdlTotalInputs s2
    }
  where
    mergeUnresolved (c1, b) (c2, _) = (c1 + c2, b)

-- | Deduplicate location fallbacks by (product, requestedLoc)
deduplicateFallbacks :: [(Text, Text, Text)] -> [(Text, Text, Text)]
deduplicateFallbacks = map (\((p, r), a) -> (p, r, a))
    . M.toList . M.fromListWith (\_ b -> b)
    . map (\(p, r, a) -> ((p, r), a))

-- | Number of resolved cross-DB links
crossDBLinksCount :: CrossDBLinkingStats -> Int
crossDBLinksCount = length . cdlLinks

-- | Number of unresolved inputs
unresolvedCount :: CrossDBLinkingStats -> Int
unresolvedCount = sum . map fst . M.elems . cdlUnresolvedProducts

-- | Cross-DB links grouped by source database
crossDBBySource :: CrossDBLinkingStats -> M.Map Text Int
crossDBBySource = M.fromListWith (+) . map (\l -> (cdlSourceDatabase l, 1)) . cdlLinks

-- | Cross-database link: records that an exchange in this database
-- sources from a supplier in another database.
--
-- At solve time, these links are used to compute demand for the
-- dependency database and chain the inventory calculations.
--
-- Note: We store both consumer and supplier as UUIDs for flexibility.
-- Consumer UUIDs are resolved to ProcessIds at solve time via dbProcessIdLookup.
-- Supplier UUIDs are looked up across loaded databases at solve time.
data CrossDBLink = CrossDBLink
    { cdlConsumerActUUID :: !UUID           -- ^ Consumer activity UUID (in this database)
    , cdlConsumerProdUUID :: !UUID          -- ^ Consumer product UUID (in this database)
    , cdlSupplierActUUID :: !UUID           -- ^ Supplier activity UUID (in another database)
    , cdlSupplierProdUUID :: !UUID          -- ^ Supplier product UUID (in another database)
    , cdlCoefficient    :: !Double          -- ^ Amount consumed per unit output of consumer
    , cdlFlowName       :: !Text            -- ^ Product name (for display/debugging)
    , cdlLocation       :: !Text            -- ^ Supplier location (for display)
    , cdlSourceDatabase :: !Text            -- ^ Source database name
    }
    deriving (Generic, NFData, Store, Show, Eq)

-- | Facteur de caractérisation (lié à une méthode LCIA)
data CF = CF
    { cfFlowId :: !UUID -- Flux biosphère concerné
    , cfCategory :: !ImpactCategory -- Catégorie d'impact
    , cfFactor :: !Double -- Facteur de caractérisation
    }

-- JSON instances for API compatibility
-- Note: ProcessId is Int16, which already has ToJSON/FromJSON instances
instance ToJSON Exchange
instance ToJSON FlowType

instance FromJSON Exchange
