{-# LANGUAGE BangPatterns #-}
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TypeFamilies #-}
{-# OPTIONS_GHC -Wno-orphans #-}

module Types (
    module Types,
    UUID,
) where

import API.JsonOptions (stripLowerPrefix)
import Control.DeepSeq (NFData)
import Data.Aeson (FromJSON (..), ToJSON (..), genericParseJSON, genericToEncoding, genericToJSON)
import Data.Int (Int32)
import qualified Data.IntSet as IS
import qualified Data.Map as M
import qualified Data.Map.Strict as MS
import qualified Data.Set as S
import Data.Store (Size (..), Store (..))
import Data.Text (Text)
import qualified Data.Text as T
import Data.UUID (UUID)
import qualified Data.UUID as UUID
import qualified Data.Vector as V
import qualified Data.Vector.Generic as VG
import qualified Data.Vector.Generic.Mutable as VGM
import qualified Data.Vector.Unboxed as VU
import GHC.Generics (Generic)

import Data.List (foldl', nub)
import Search.BM25.Types (BM25Index)
import SynonymDB (normalizeName)
import SynonymDB.Types (SynonymDB)

-- | Orphan Store instance for UUID (16 bytes, host-native word order)
instance Store UUID where
    size = ConstSize 16
    poke uuid =
        let (a, b, c, d) = UUID.toWords uuid
         in poke a >> poke b >> poke c >> poke d
    peek = UUID.fromWords <$> peek <*> peek <*> peek <*> peek

-- Note: UUID is now Data.UUID.UUID (16 bytes) instead of Text (~80+ bytes)
-- This saves ~2-3GB of RAM by reducing memory footprint from ~100,000+ UUID instances
-- NFData instance is provided by the uuid package; Store instance defined above

{- | Process identifier - compact Int32 index for efficient matrix operations
Maps to (activityUUID, productUUID) via Database.dbProcessIdTable
Based on EcoSpold filename pattern {activity_uuid}_{product_uuid}.spold
-}
type ProcessId = Int32

-- | Flow type: Technosphere (exchange between activities) or Biosphere (exchange with the environment)
data FlowType = Technosphere | Biosphere
    deriving (Eq, Ord, Show, Generic, NFData, Store)

-- | Unit representation (kg, MJ, m³, etc.)
data Unit = Unit
    { unitId :: !UUID -- Unique unit identifier
    , unitName :: !Text -- Unit name (e.g. "kg", "kilogram")
    , unitSymbol :: !Text -- Symbol (e.g. "kg", "MJ")
    , unitComment :: !Text -- Description/comment
    }
    deriving (Generic, NFData, Store)

{- | Substance - groups flows with the same chemical identity across databases
Used for flow matching between different LCA databases (ecoinvent, ILCD, SimaPro)
The substanceId links to the flow_mapping.json generated by the Python ETL script
-}
data Substance = Substance
    { substanceId :: !Int -- Unique identifier within the mapping
    , substanceCanonicalName :: !Text -- Primary name for display
    , substanceCAS :: !(Maybe Text) -- CAS number (e.g. "7439-97-6" for Mercury)
    , substanceSynonyms :: !(S.Set Text) -- All normalized synonyms (lowercase)
    }
    deriving (Eq, Show, Generic, NFData, Store)

-- | Flow representation (material, energy, emission, etc.)
data Flow = Flow
    { flowId :: !UUID -- Flow identifier
    , flowName :: !Text -- Human-readable name
    , flowCategory :: !Text -- Category/compartment (e.g. air, water, soil, resource)
    , flowSubcompartment :: !(Maybe Text) -- Sub-compartment (e.g. "urban air", "river water")
    , flowUnitId :: !UUID -- Reference to default unit in UnitDB
    , flowType :: !FlowType -- Flow type
    , flowSynonyms :: !(M.Map Text (S.Set Text)) -- Synonyms by language (e.g. "en" -> {"BaP", "benzo[a]pyrene"})
    , flowCAS :: !(Maybe Text) -- CAS number for substance identification
    , flowSubstanceId :: !(Maybe Int) -- Link to Substance in FlowMappingData
    }
    deriving (Generic, NFData, Store)

-- | Exchange in an activity - Mirrors EcoSpold intermediateExchange/elementaryExchange structure
data Exchange
    = TechnosphereExchange
        { techFlowId :: !UUID -- Flow being exchanged
        , techAmount :: !Double -- Quantity exchanged
        , techUnitId :: !UUID -- Unit of measurement
        , techIsInput :: !Bool -- True if input
        , techIsReference :: !Bool -- True if reference product (main output)
        , techActivityLinkId :: !UUID -- Target activity ID (backward compatibility)
        , techProcessLinkId :: !(Maybe ProcessId) -- Target process ID (new field)
        , techLocation :: !Text -- Supplier location (EcoSpold1) or "" (EcoSpold2)
        }
    | BiosphereExchange
        { bioFlowId :: !UUID -- Flow being exchanged
        , bioAmount :: !Double -- Quantity exchanged
        , bioUnitId :: !UUID -- Unit of measurement
        , bioIsInput :: !Bool -- True for resource extraction, False for emissions
        , bioLocation :: !Text -- Exchange location (EcoSpold1) or "" (EcoSpold2)
        }
    deriving (Generic, NFData, Store)

-- | Helper functions for Exchange variants
exchangeFlowId :: Exchange -> UUID
exchangeFlowId (TechnosphereExchange fid _ _ _ _ _ _ _) = fid
exchangeFlowId (BiosphereExchange fid _ _ _ _) = fid

exchangeAmount :: Exchange -> Double
exchangeAmount (TechnosphereExchange _ amt _ _ _ _ _ _) = amt
exchangeAmount (BiosphereExchange _ amt _ _ _) = amt

exchangeUnitId :: Exchange -> UUID
exchangeUnitId (TechnosphereExchange _ _ uid _ _ _ _ _) = uid
exchangeUnitId (BiosphereExchange _ _ uid _ _) = uid

exchangeIsInput :: Exchange -> Bool
exchangeIsInput (TechnosphereExchange _ _ _ isInp _ _ _ _) = isInp
exchangeIsInput (BiosphereExchange _ _ _ isInp _) = isInp

exchangeIsReference :: Exchange -> Bool
exchangeIsReference (TechnosphereExchange _ _ _ _ isRef _ _ _) = isRef
exchangeIsReference BiosphereExchange{} = False -- Biosphere exchanges are never reference products

-- | Get activity link ID (backward compatibility)
exchangeActivityLinkId :: Exchange -> Maybe UUID
exchangeActivityLinkId (TechnosphereExchange _ _ _ _ _ linkId _ _) =
    if linkId == UUID.nil then Nothing else Just linkId
exchangeActivityLinkId BiosphereExchange{} = Nothing

-- | Get process link ID (new field)
exchangeProcessLinkId :: Exchange -> Maybe ProcessId
exchangeProcessLinkId (TechnosphereExchange _ _ _ _ _ _ processLinkId _) = processLinkId
exchangeProcessLinkId BiosphereExchange{} = Nothing

-- | Get exchange location (for EcoSpold1 supplier lookup)
exchangeLocation :: Exchange -> Text
exchangeLocation (TechnosphereExchange _ _ _ _ _ _ _ loc) = loc
exchangeLocation (BiosphereExchange _ _ _ _ loc) = loc

-- | Check if exchange is technosphere
isTechnosphereExchange :: Exchange -> Bool
isTechnosphereExchange TechnosphereExchange{} = True
isTechnosphereExchange BiosphereExchange{} = False

-- | Check if exchange is biosphere
isBiosphereExchange :: Exchange -> Bool
isBiosphereExchange = not . isTechnosphereExchange

{- | Activity's reference-product amount used to normalize its matrix column.
Net output = sum of reference outputs minus self-loop consumption; falls back
to reference inputs (treatment processes) or 1.0 when nothing else applies.
Self-loops require both activityLinkId == activityUUID AND flowId == productUUID,
so cross-product inputs in multi-output processes are not mistakenly subtracted.
-}
activityNormFactor :: Activity -> (UUID, UUID) -> Double
activityNormFactor act (actUUID, prodUUID) =
    let isSelfLoop ex = case exchangeActivityLinkId ex of
            Just linkUUID -> linkUUID == actUUID && exchangeFlowId ex == prodUUID
            Nothing -> False
        refOutputs =
            sum
                [ exchangeAmount ex
                | ex <- exchanges act
                , exchangeIsReference ex
                , not (exchangeIsInput ex)
                ]
        refInputs =
            sum
                [ abs (exchangeAmount ex)
                | ex <- exchanges act
                , exchangeIsReference ex
                , exchangeIsInput ex
                ]
        internalConsumption =
            sum
                [ exchangeAmount ex
                | ex <- exchanges act
                , isTechnosphereExchange ex
                , exchangeIsInput ex
                , not (exchangeIsReference ex)
                , isSelfLoop ex
                ]
        netOutput = if refOutputs > 1e-15 then refOutputs - internalConsumption else 0.0
     in if netOutput > 1e-15
            then netOutput
            else
                if refInputs > 1e-15
                    then refInputs
                    else 1.0

-- | Get unit information for an exchange
getUnitForExchange :: UnitDB -> Exchange -> Maybe Unit
getUnitForExchange unitDB exchange = M.lookup (exchangeUnitId exchange) unitDB

-- | Get unit name for an exchange (fallback to "unknown" if not found)
getUnitNameForExchange :: UnitDB -> Exchange -> Text
getUnitNameForExchange unitDB exchange =
    maybe "unknown" unitName (getUnitForExchange unitDB exchange)

-- | Get unit information for a flow
getUnitForFlow :: UnitDB -> Flow -> Maybe Unit
getUnitForFlow unitDB flow = M.lookup (flowUnitId flow) unitDB

-- | Get unit name for a flow (fallback to "unknown" if not found)
getUnitNameForFlow :: UnitDB -> Flow -> Text
getUnitNameForFlow unitDB flow =
    maybe "unknown" unitName (getUnitForFlow unitDB flow)

{- | Base LCA activity
Note: ProcessId is the index in dbActivities vector, UUIDs stored in dbProcessIdTable
-}
data Activity = Activity
    { activityName :: !Text -- Name
    , activityDescription :: ![Text] -- General description (generalComment) by paragraphs
    , activitySynonyms :: !(M.Map Text (S.Set Text)) -- Synonyms by language, same structure as flows
    , activityClassification :: !(M.Map Text Text) -- Classifications (ISIC, CPC, etc.)
    , activityLocation :: !Text -- Location code (e.g. FR, RER)
    , activityUnit :: !Text -- Reference unit
    , exchanges :: ![Exchange] -- List of exchanges
    , activityParams :: !(M.Map Text Double) -- Resolved SimaPro parameter values
    , activityParamExprs :: !(M.Map Text Text) -- Raw SimaPro parameter expressions (for re-evaluation)
    }
    deriving (Generic, NFData, Store)

-- | LCA computation tree (recursive representation)
data ActivityTree
    = Leaf !Activity
    | Node !Activity ![(Double, ActivityTree)] -- Activities and weighted sub-activities

-- | Loop-aware tree for SVG export
data LoopAwareTree
    = TreeLeaf !Activity
    | TreeNode !Activity ![(Double, Flow, LoopAwareTree)] -- Activity + (quantity, flow, subtree)
    | TreeLoop !UUID !Text !Int -- Loop reference: UUID + ActivityName + Depth

-- | Flow database (deduplicated)
type FlowDB = M.Map UUID Flow

-- | Unit database (deduplicated)
type UnitDB = M.Map UUID Unit

{- | Temporary Map structure used during database loading phase
Maps from (activityUUID, productUUID) pairs extracted from .spold filenames
This is converted to ActivityDB Vector during database construction
-}
type ActivityMap = M.Map (UUID, UUID) Activity

{- | Activity database - Vector for direct indexing by ProcessId (Int32)
Each spold file (activity_uuid_product_uuid.spold) becomes a separate entry
-}
type ActivityDB = V.Vector Activity

-- | Index by activity name - case-insensitive name lookup
type NameIndex = M.Map Text [UUID] -- Name -> [ActivityUUID]

-- | Index by location - geographic search
type LocationIndex = M.Map Text [UUID] -- Location -> [ActivityUUID]

-- | Index by flow - find activities that use a given flow
type FlowIndex = M.Map UUID [UUID] -- FlowID -> [ActivityUUID]

-- | Index by flow category - search by flow type
type FlowCategoryIndex = M.Map Text [UUID] -- Category -> [FlowUUID]

-- | Index by flow type - separates Technosphere/Biosphere
type FlowTypeIndex = M.Map FlowType [UUID] -- FlowType -> [FlowUUID]

-- | Index of exchanges by flow - find all exchanges using a flow
type ExchangeIndex = M.Map UUID [(UUID, Exchange)] -- FlowID -> [(ActivityID, Exchange)]

-- | Index of exchanges by activity - fast exchange lookup per activity
type ActivityExchangeIndex = M.Map UUID [Exchange] -- ActivityID -> [Exchange]

-- | Index of reference products - all primary outputs
type ReferenceProductIndex = M.Map UUID [(UUID, Exchange)] -- FlowID -> [(ActivityID, Exchange)]

-- | Index of inputs by activity - separates inputs/outputs
type ActivityInputIndex = M.Map UUID [Exchange] -- ActivityID -> [Input Exchanges]

-- | Index of outputs by activity - separates inputs/outputs
type ActivityOutputIndex = M.Map UUID [Exchange] -- ActivityID -> [Output Exchanges]

-- | Index by reference unit - unit-based activity search
type ActivityUnitIndex = M.Map Text [UUID] -- Unit -> [ActivityUUID]

{- | Complete index structure for efficient searches
Memory optimization: Removed unused exchange indexes that were duplicating 600K Exchange records
across 5 maps (idxExchangeByFlow, idxExchangeByActivity, idxReferenceProducts,
idxInputsByActivity, idxOutputsByActivity) - saves ~3-4GB RAM
-}
data Indexes = Indexes
    { -- Activity-level indexes
      idxByName :: !NameIndex -- Search activities by name
    , idxByLocation :: !LocationIndex -- Search activities by location
    , idxByFlow :: !FlowIndex -- Search activities using a flow
    , idxByUnit :: !ActivityUnitIndex -- Search activities by reference unit
    -- Flow-level indexes
    , idxFlowByCategory :: !FlowCategoryIndex -- Search flows by category
    , idxFlowByType :: !FlowTypeIndex -- Search flows by type
    -- Note: Exchange-level indexes removed - exchanges can be accessed directly from Activity.exchanges
    }
    deriving (Generic, NFData, Store)

{- | Sparse matrix coordinate triplet (row, col, value)
Using Int32 for matrix indices to support large databases (up to 2 billion activities)
Unboxed to eliminate per-element boxing overhead (~48 bytes → 16 bytes per triple)
With ~800K triples, this saves ~25MB + significant GC pressure
-}
data SparseTriple = SparseTriple {-# UNPACK #-} !Int32 {-# UNPACK #-} !Int32 {-# UNPACK #-} !Double
    deriving (Eq, Show, Generic)

-- Manual Unbox instance for SparseTriple to enable VU.Vector storage
newtype instance VU.MVector s SparseTriple = MV_SparseTriple (VU.MVector s (Int32, Int32, Double))
newtype instance VU.Vector SparseTriple = V_SparseTriple (VU.Vector (Int32, Int32, Double))

instance VGM.MVector VU.MVector SparseTriple where
    {-# INLINE basicLength #-}
    {-# INLINE basicUnsafeSlice #-}
    {-# INLINE basicOverlaps #-}
    {-# INLINE basicUnsafeNew #-}
    {-# INLINE basicInitialize #-}
    {-# INLINE basicUnsafeRead #-}
    {-# INLINE basicUnsafeWrite #-}
    basicLength (MV_SparseTriple v) = VGM.basicLength v
    basicUnsafeSlice i n (MV_SparseTriple v) = MV_SparseTriple $ VGM.basicUnsafeSlice i n v
    basicOverlaps (MV_SparseTriple v1) (MV_SparseTriple v2) = VGM.basicOverlaps v1 v2
    basicUnsafeNew n = MV_SparseTriple <$> VGM.basicUnsafeNew n
    basicInitialize (MV_SparseTriple v) = VGM.basicInitialize v
    basicUnsafeRead (MV_SparseTriple v) i = do
        (r, c, val) <- VGM.basicUnsafeRead v i
        return $ SparseTriple r c val
    basicUnsafeWrite (MV_SparseTriple v) i (SparseTriple r c val) =
        VGM.basicUnsafeWrite v i (r, c, val)

instance VG.Vector VU.Vector SparseTriple where
    {-# INLINE basicUnsafeFreeze #-}
    {-# INLINE basicUnsafeThaw #-}
    {-# INLINE basicLength #-}
    {-# INLINE basicUnsafeSlice #-}
    {-# INLINE basicUnsafeIndexM #-}
    basicUnsafeFreeze (MV_SparseTriple v) = V_SparseTriple <$> VG.basicUnsafeFreeze v
    basicUnsafeThaw (V_SparseTriple v) = MV_SparseTriple <$> VG.basicUnsafeThaw v
    basicLength (V_SparseTriple v) = VG.basicLength v
    basicUnsafeSlice i n (V_SparseTriple v) = V_SparseTriple $ VG.basicUnsafeSlice i n v
    basicUnsafeIndexM (V_SparseTriple v) i = do
        (r, c, val) <- VG.basicUnsafeIndexM v i
        return $ SparseTriple r c val

instance VU.Unbox SparseTriple

-- Store instance for cache serialization
instance Store SparseTriple where
    size = ConstSize 16 -- Int32 (4) + Int32 (4) + Double (8)
    poke (SparseTriple r c v) = poke r >> poke c >> poke v
    peek = SparseTriple <$> peek <*> peek <*> peek

-- NFData derived via Generic
instance NFData SparseTriple

-- | Store instance for VU.Vector SparseTriple (store has no built-in instance for custom Unbox types)
instance Store (VU.Vector SparseTriple) where
    size = VarSize $ \v -> 8 + VU.length v * 16
    poke v = do
        poke (VU.length v)
        VU.mapM_ poke v
    peek = do
        n <- peek
        VU.replicateM n peek

-- | Compute serialized size for a Store value
getSize :: (Store a) => a -> Int
getSize x = case size of
    ConstSize n -> n
    VarSize f -> f x

-- | Pre-computed matrix factorization for fast inventory calculations
data MatrixFactorization = MatrixFactorization
    { mfSystemMatrix :: !(VU.Vector SparseTriple) -- Cached (I - A) system matrix (unboxed)
    , mfActivityCount :: !Int32 -- Matrix dimension
    , mfDatabaseId :: !Text -- Database identifier for per-database cache lookup
    }
    deriving (Generic, NFData, Store)

{- | Index for looking up activities by their reference product attributes
Used for: (1) upstream link resolution for SimaPro data, (2) future product search
-}
data ProductIndex = ProductIndex
    { piByUUID :: !(M.Map UUID ProcessId) -- Product flow UUID → ProcessId (for upstream links)
    , piByName :: !(M.Map Text [ProcessId]) -- Normalized product name → [ProcessId] (for search)
    , piByLocation :: !(M.Map Text [ProcessId]) -- Location → [ProcessId] (for search)
    }
    deriving (Generic, NFData, Store)

-- | Empty product index (used as default when loading old cache files)
emptyProductIndex :: ProductIndex
emptyProductIndex = ProductIndex M.empty M.empty M.empty

-- | Complete database with indexes for efficient searches
data Database = Database
    { -- UUID interning tables for ProcessId ↔ (UUID, UUID) conversion
      dbProcessIdTable :: !(V.Vector (UUID, UUID)) -- ProcessId (Int32) → (activityUUID, productUUID)
    , dbProcessIdLookup :: !(M.Map (UUID, UUID) ProcessId) -- reverse lookup
    , dbActivityUUIDIndex :: !(M.Map UUID ProcessId) -- Activity UUID → ProcessId (for O(1) lookups)
    , dbActivityProductsIndex :: !(M.Map UUID [ProcessId]) -- Activity UUID → all ProcessIds (for multi-product activities)
    , dbProductIndex :: !ProductIndex -- Product flow → ProcessId lookups (for SimaPro links & product search)
    , dbActivities :: !ActivityDB -- Vector of activities indexed by ProcessId
    , dbFlows :: !FlowDB
    , dbUnits :: !UnitDB
    , dbIndexes :: !Indexes
    , -- Pre-computed sparse matrices for efficient LCA calculations (unboxed for memory efficiency)
      dbTechnosphereTriples :: !(VU.Vector SparseTriple) -- A matrix: activities × activities (sparse, unboxed)
    , dbBiosphereTriples :: !(VU.Vector SparseTriple) -- B matrix: biosphere flows × activities (sparse, unboxed)
    , dbActivityIndex :: !(V.Vector Int32) -- ProcessId → matrix index mapping (direct vector indexing)
    , dbBiosphereFlows :: !(V.Vector UUID) -- Ordered vector of biosphere flow UUIDs (source of truth for indexing, strict for memory efficiency)
    , dbActivityCount :: !Int32 -- Number of activities (matrix dimension)
    , dbBiosphereCount :: !Int32 -- Number of biosphere flows (matrix dimension)
    -- Cross-database linking (serialized to cache)
    , dbCrossDBLinks :: ![CrossDBLink] -- Cross-database supplier links (for chained solving)
    , dbDependsOn :: ![Text] -- Names of databases this database depends on
    -- Linking statistics (serialized to cache for setup page)
    , dbLinkingStats :: !CrossDBLinkingStats -- Cross-DB linking statistics (completeness, fallbacks, etc.)
    -- Runtime-only fields (not serialized to cache)
    , dbSynonymDB :: !(Maybe SynonymDB) -- Embedded synonym database for flow matching
    , dbFlowsByName :: !(M.Map Text [Flow]) -- Biosphere flow name index for LCIA matching
    , dbFlowsByCAS :: !(M.Map Text [Flow]) -- CAS → biosphere flows for LCIA matching
    -- Product name search index: word token → ProcessId set (built at runtime)
    , dbProductSearchIndex :: !(M.Map Text IS.IntSet)
    , -- BM25 ranking index (built at runtime, not serialized)
      dbBM25Index :: !(Maybe BM25Index)
    }
    deriving (Generic, NFData)

{- | Custom Store instance for Database
Only serializes persistent fields (not runtime-only: factorization, synonymDB, flowsByName)
-}
instance Store Database where
    size = VarSize $ \db ->
        getSize (dbProcessIdTable db)
            + getSize (dbProcessIdLookup db)
            + getSize (dbActivityUUIDIndex db)
            + getSize (dbActivityProductsIndex db)
            + getSize (dbProductIndex db)
            + getSize (dbActivities db)
            + getSize (dbFlows db)
            + getSize (dbUnits db)
            + getSize (dbIndexes db)
            + getSize (dbTechnosphereTriples db)
            + getSize (dbBiosphereTriples db)
            + getSize (dbActivityIndex db)
            + getSize (dbBiosphereFlows db)
            + getSize (dbActivityCount db)
            + getSize (dbBiosphereCount db)
            + getSize (dbCrossDBLinks db)
            + getSize (dbDependsOn db)
            + getSize (dbLinkingStats db)

    poke db = do
        poke (dbProcessIdTable db)
        poke (dbProcessIdLookup db)
        poke (dbActivityUUIDIndex db)
        poke (dbActivityProductsIndex db)
        poke (dbProductIndex db)
        poke (dbActivities db)
        poke (dbFlows db)
        poke (dbUnits db)
        poke (dbIndexes db)
        poke (dbTechnosphereTriples db)
        poke (dbBiosphereTriples db)
        poke (dbActivityIndex db)
        poke (dbBiosphereFlows db)
        poke (dbActivityCount db)
        poke (dbBiosphereCount db)
        -- Cross-database linking fields
        poke (dbCrossDBLinks db)
        poke (dbDependsOn db)
        poke (dbLinkingStats db)

    -- Runtime-only fields are NOT serialized

    peek = do
        processIdTable <- peek
        processIdLookup <- peek
        activityUUIDIndex <- peek
        activityProductsIndex <- peek
        productIndex <- peek
        activities <- peek
        flows <- peek
        units <- peek
        indexes <- peek
        techTriples <- peek
        bioTriples <- peek
        activityIndex <- peek
        biosphereFlows <- peek
        activityCount <- peek
        biosphereCount <- peek
        crossDBLinks <- peek
        dependsOn <- peek
        linkingStats <- peek
        return
            Database
                { dbProcessIdTable = processIdTable
                , dbProcessIdLookup = processIdLookup
                , dbActivityUUIDIndex = activityUUIDIndex
                , dbActivityProductsIndex = activityProductsIndex
                , dbProductIndex = productIndex
                , dbActivities = activities
                , dbFlows = flows
                , dbUnits = units
                , dbIndexes = indexes
                , dbTechnosphereTriples = techTriples
                , dbBiosphereTriples = bioTriples
                , dbActivityIndex = activityIndex
                , dbBiosphereFlows = biosphereFlows
                , dbActivityCount = activityCount
                , dbBiosphereCount = biosphereCount
                , -- Cross-database linking fields
                  dbCrossDBLinks = crossDBLinks
                , dbDependsOn = dependsOn
                , dbLinkingStats = linkingStats
                , -- Runtime-only fields set to defaults
                  dbSynonymDB = Nothing
                , dbFlowsByName = M.empty
                , dbFlowsByCAS = M.empty
                , dbProductSearchIndex = M.empty
                , dbBM25Index = Nothing
                }

-- | Helper functions for ProcessId and Database operations

-- | Get activity by ProcessId (direct vector indexing)
getActivity :: Database -> ProcessId -> Maybe Activity
getActivity db pid
    | pid >= 0 && fromIntegral pid < V.length (dbActivities db) =
        Just $ dbActivities db V.! fromIntegral pid
    | otherwise = Nothing

-- | Find ProcessId from UUID pair
findProcessId :: Database -> UUID -> UUID -> Maybe ProcessId
findProcessId db actUUID prodUUID =
    M.lookup (actUUID, prodUUID) (dbProcessIdLookup db)

{- | Find any ProcessId matching an activity UUID
Returns the first ProcessId found with the given activity UUID.
ESSENTIAL for EcoSpold data: exchange links only contain activity UUIDs (not full ProcessIds),
so we must translate from UUID → ProcessId to handle multi-product activities.
-}
findProcessIdByActivityUUID :: Database -> UUID -> Maybe ProcessId
findProcessIdByActivityUUID db searchUUID =
    M.lookup searchUUID (dbActivityUUIDIndex db)

{- | Find activity by activity UUID (returns first matching product)
ESSENTIAL for EcoSpold data: exchange links only contain activity UUIDs (not full ProcessIds).
When multiple products exist for one activity, this returns an arbitrary match.
Uses O(1) Map lookup for efficient resolution
-}
findActivityByActivityUUID :: Database -> UUID -> Maybe Activity
findActivityByActivityUUID db searchUUID = do
    pid <- M.lookup searchUUID (dbActivityUUIDIndex db)
    getActivity db pid

{- | Find supplier ProcessId by product flow UUID
ESSENTIAL for SimaPro data: exchanges have techActivityLinkId = nil, but techFlowId is valid.
Uses the ProductIndex to resolve the supplier activity from the product flow.
-}
findProcessIdByProductFlow :: Database -> UUID -> Maybe ProcessId
findProcessIdByProductFlow db flowUUID =
    M.lookup flowUUID (piByUUID $ dbProductIndex db)

{- | Search products by name (for future product search feature)
Returns all ProcessIds that produce products matching the given name
-}
searchProductsByName :: Database -> Text -> [ProcessId]
searchProductsByName db query =
    M.findWithDefault [] (T.toLower query) (piByName $ dbProductIndex db)

{- | Search products by location (for future product search feature)
Returns all ProcessIds that produce products at the given location
-}
searchProductsByLocation :: Database -> Text -> [ProcessId]
searchProductsByLocation db loc =
    M.findWithDefault [] loc (piByLocation $ dbProductIndex db)

-- | Convert ProcessId to UUID pair
processIdToUUIDs :: Database -> ProcessId -> Maybe (UUID, UUID)
processIdToUUIDs db pid
    | pid >= 0 && fromIntegral pid < V.length (dbProcessIdTable db) =
        Just $ dbProcessIdTable db V.! fromIntegral pid
    | otherwise = Nothing

-- | Convert ProcessId to Text representation for display (activityUUID_productUUID)
processIdToText :: Database -> ProcessId -> Text
processIdToText db pid =
    case processIdToUUIDs db pid of
        Just (actUUID, prodUUID) -> UUID.toText actUUID <> "_" <> UUID.toText prodUUID
        Nothing -> "invalid-process-id-" <> T.pack (show pid)

-- | Parse ProcessId from filename stem (requires Database for lookup)
parseProcessId :: Database -> Text -> Maybe ProcessId
parseProcessId db filename = case T.splitOn "_" filename of
    [actUUIDText, prodUUIDText] | not (T.null actUUIDText) && not (T.null prodUUIDText) ->
        case (UUID.fromText actUUIDText, UUID.fromText prodUUIDText) of
            (Just actUUID, Just prodUUID) -> findProcessId db actUUID prodUUID
            _ -> Nothing
    _ -> Nothing

-- | Add SynonymDB to a Database (used after loading from cache)
addSynonymDBToDatabase :: Database -> SynonymDB -> Database
addSynonymDBToDatabase db synDB = db{dbSynonymDB = Just synDB}

{- | Build the flow name index from biosphere flows only.
Groups flows by their normalized names for efficient LCIA lookup.
-}
buildFlowNameIndex :: FlowDB -> S.Set UUID -> M.Map Text [Flow]
buildFlowNameIndex flowDB bioUUIDs =
    M.fromListWith (++) $ concatMap flowEntries bioFlows
  where
    bioFlows = filter (\f -> S.member (flowId f) bioUUIDs) (M.elems flowDB)
    flowEntries f =
        let primary = normalizeName (flowName f)
            synKeys =
                [ normalizeName syn
                | syns <- M.elems (flowSynonyms f)
                , syn <- S.toList syns
                ]
         in [(k, [f]) | k <- nub (primary : synKeys)]

-- | Build CAS index from biosphere flows
buildFlowCASIndex :: FlowDB -> S.Set UUID -> M.Map Text [Flow]
buildFlowCASIndex flowDB bioUUIDs =
    M.fromListWith
        (++)
        [ (cas, [f])
        | f <- M.elems flowDB
        , S.member (flowId f) bioUUIDs
        , Just cas <- [flowCAS f]
        , not (T.null cas)
        ]

-- | Add biosphere flow indexes (name + CAS) and search index to a Database
addFlowNameIndexToDatabase :: Database -> Database
addFlowNameIndexToDatabase db =
    let bioUUIDs = S.fromList (V.toList (dbBiosphereFlows db))
     in db
            { dbFlowsByName = buildFlowNameIndex (dbFlows db) bioUUIDs
            , dbFlowsByCAS = buildFlowCASIndex (dbFlows db) bioUUIDs
            , dbProductSearchIndex = buildProductSearchIndex (dbActivities db) (dbFlows db)
            }

{- | Build word-token product search index: lowercased word → IntSet of ProcessIds
Tokenizes reference product flow names so product search can use index intersection.
-}
buildProductSearchIndex :: V.Vector Activity -> M.Map UUID Flow -> M.Map Text IS.IntSet
buildProductSearchIndex activities flowDb =
    V.ifoldl' addActivity M.empty activities
  where
    addActivity !acc i a =
        let pid = fromIntegral i
            productWords =
                [ w
                | ex <- exchanges a
                , exchangeIsReference ex
                , not (exchangeIsInput ex)
                , Just flow <- [M.lookup (exchangeFlowId ex) flowDb]
                , w <- T.words (T.toLower (flowName flow))
                , not (T.null w)
                ]
         in foldl' (\m w -> MS.insertWith IS.union w (IS.singleton pid) m) acc productWords

{- | Add both SynonymDB and flow name index to a Database
Convenience function for post-load initialization
-}
initializeRuntimeFields :: Database -> SynonymDB -> Database
initializeRuntimeFields db synDB =
    let db' = addSynonymDBToDatabase db synDB
     in addFlowNameIndexToDatabase db'

{- | Simplified version without indexes (for loading compatibility)
Used during database loading, before conversion to final Vector structure
-}
data SimpleDatabase = SimpleDatabase
    { sdbActivities :: !ActivityMap -- Temporary Map structure
    , sdbFlows :: !FlowDB
    , sdbUnits :: !UnitDB
    }
    deriving (Generic, Store)

{- | Reconstruct SimpleDatabase from a fully-built Database
Used to skip re-parsing when a valid cache exists during staging
-}
toSimpleDatabase :: Database -> SimpleDatabase
toSimpleDatabase db =
    SimpleDatabase
        { sdbActivities = M.fromList $ V.toList $ V.zipWith (,) (dbProcessIdTable db) (dbActivities db)
        , sdbFlows = dbFlows db
        , sdbUnits = dbUnits db
        }

-- | Impact category (e.g. Climate change)
data ImpactCategory = ImpactCategory
    { categoryId :: !Text
    , categoryName :: !Text
    }
    deriving (Eq, Ord, Show)

-- | Blocking reason for cross-database linking failure
data LinkBlocker
    = -- | Product not found at all
      NoNameMatch
    | -- | queryUnit, supplierUnit
      UnitIncompatible !Text !Text
    | -- | requestedLoc (no fallback found above threshold)
      LocationUnavailable !Text
    deriving (Show, Eq, Generic, NFData, Store)

{- | Statistics from cross-database linking
Only essential state is stored; counts are derived via accessor functions.
-}
data CrossDBLinkingStats = CrossDBLinkingStats
    { cdlLinks :: ![CrossDBLink]
    -- ^ Resolved cross-DB links
    , cdlUnresolvedProducts :: !(M.Map Text (Int, LinkBlocker))
    -- ^ Product name -> (count, reason)
    , cdlUnknownUnits :: !(S.Set Text)
    -- ^ Unknown units from sdbUnits
    , cdlLocationFallbacks :: ![(Text, Text, Text)]
    -- ^ (product, requestedLoc, actualLoc)
    , cdlTotalInputs :: !Int
    -- ^ Total technosphere inputs at time of linking
    }
    deriving (Generic, NFData, Store)

-- | Empty stats
emptyCrossDBLinkingStats :: CrossDBLinkingStats
emptyCrossDBLinkingStats = CrossDBLinkingStats [] M.empty S.empty [] 0

-- | Merge two CrossDBLinkingStats
mergeCrossDBStats :: CrossDBLinkingStats -> CrossDBLinkingStats -> CrossDBLinkingStats
mergeCrossDBStats s1 s2 =
    CrossDBLinkingStats
        { cdlLinks = cdlLinks s1 ++ cdlLinks s2
        , cdlUnresolvedProducts = M.unionWith mergeUnresolved (cdlUnresolvedProducts s1) (cdlUnresolvedProducts s2)
        , cdlUnknownUnits = S.union (cdlUnknownUnits s1) (cdlUnknownUnits s2)
        , cdlLocationFallbacks = cdlLocationFallbacks s1 ++ cdlLocationFallbacks s2
        , cdlTotalInputs = cdlTotalInputs s1 + cdlTotalInputs s2
        }
  where
    mergeUnresolved (c1, b) (c2, _) = (c1 + c2, b)

-- | Deduplicate location fallbacks by (product, requestedLoc)
deduplicateFallbacks :: [(Text, Text, Text)] -> [(Text, Text, Text)]
deduplicateFallbacks =
    map (\((p, r), a) -> (p, r, a))
        . M.toList
        . M.fromListWith (\_ b -> b)
        . map (\(p, r, a) -> ((p, r), a))

-- | Number of resolved cross-DB links
crossDBLinksCount :: CrossDBLinkingStats -> Int
crossDBLinksCount = length . cdlLinks

-- | Number of unresolved inputs
unresolvedCount :: CrossDBLinkingStats -> Int
unresolvedCount = sum . map fst . M.elems . cdlUnresolvedProducts

-- | Cross-DB links grouped by source database
crossDBBySource :: CrossDBLinkingStats -> M.Map Text Int
crossDBBySource = M.fromListWith (+) . map (\l -> (cdlSourceDatabase l, 1)) . cdlLinks

{- | Cross-database link: records that an exchange in this database
sources from a supplier in another database.

At solve time, these links are used to compute demand for the
dependency database and chain the inventory calculations.

Note: We store both consumer and supplier as UUIDs for flexibility.
Consumer UUIDs are resolved to ProcessIds at solve time via dbProcessIdLookup.
Supplier UUIDs are looked up across loaded databases at solve time.
-}
data CrossDBLink = CrossDBLink
    { cdlConsumerActUUID :: !UUID
    -- ^ Consumer activity UUID (in this database)
    , cdlConsumerProdUUID :: !UUID
    -- ^ Consumer product UUID (in this database)
    , cdlSupplierActUUID :: !UUID
    -- ^ Supplier activity UUID (in another database)
    , cdlSupplierProdUUID :: !UUID
    -- ^ Supplier product UUID (in another database)
    , cdlCoefficient :: !Double
    -- ^ Amount consumed per unit output of consumer
    , cdlExchangeUnit :: !Text
    -- ^ Consumer's exchange unit (converted to supplier refUnit at matrix-build time)
    , cdlFlowName :: !Text
    -- ^ Product name (for display/debugging)
    , cdlLocation :: !Text
    -- ^ Supplier location (for display)
    , cdlSourceDatabase :: !Text
    -- ^ Source database name
    }
    deriving (Generic, NFData, Store, Show, Eq)

-- | Characterization factor (associated with an LCIA method)
data CF = CF
    { cfFlowId :: !UUID -- Biosphere flow being characterized
    , cfCategory :: !ImpactCategory -- Impact category
    , cfFactor :: !Double -- Characterization factor
    }

-- JSON instances for API compatibility
-- Note: ProcessId is Int32, which already has ToJSON/FromJSON instances
instance ToJSON Exchange where
    toJSON = genericToJSON stripLowerPrefix
    toEncoding = genericToEncoding stripLowerPrefix
instance ToJSON FlowType

instance FromJSON Exchange where
    parseJSON = genericParseJSON stripLowerPrefix
